/** Inhalt Teil 2 — Block B: Regulatorik (Sprecher:in 2). */

const BLOCK_B = [
  {
    layout: 'divider',
    num: 'B',
    title: 'Regulatorik',
    subtitle: 'Was Pflicht ist, was freiwillig — und was überraschend\ngar nicht gilt',
    speaker: 2,
    minutes: 10,
    notes: [
      'Vielen Dank. Ich übernehme die Regulatorik und beginne mit einer Bitte: Trennen Sie im Kopf drei Dinge, die in solchen Projekten regelmäßig vermischt werden.',
      'Es gibt Pflicht, es gibt freiwilligen Mehrwert, und es gibt Marketing. Alle drei können sinnvoll sein — aber nur das Erste hat eine Frist und ein Bußgeld.',
      'Ich gehe vier Fragen durch: Was verlangt die Entwaldungsverordnung? Ab wann? Wen von uns betrifft was? Und was von dem, was die Aufgabenstellung als Pflicht bezeichnet, ist tatsächlich keine.',
    ].join(' '),
  },
  {
    layout: 'cards',
    kicker: 'EUDR — Verordnung (EU) 2023/1115',
    title: 'Was die Entwaldungsverordnung tatsächlich verlangt',
    speaker: 2,
    cols: 3,
    cards: [
      { badge: '1', title: 'Geolokation jeder Parzelle', text: 'Polygone für Flächen über vier Hektar, Punktkoordinaten darunter. Nicht nur formal vorhanden — die Daten müssen einer Satellitenprüfung und einem Behördenaudit standhalten.' },
      { badge: '2', title: 'Entwaldungsfrei nach Stichtag', text: 'Nachweis, dass auf der Fläche seit dem 31.12.2020 kein Wald verloren ging. Praktisch: Abgleich der Polygone gegen Waldverlustdaten.' },
      { badge: '3', title: 'Legalität im Erzeugerland', text: 'Landnutzungsrecht, Arbeitsrecht, Steuern, Handelsrecht — nach dem Recht des Ursprungslandes, nicht nach EU-Recht.' },
      { badge: '4', title: 'Risikobewertung und -minderung', text: 'Dokumentiert. Ist das Risiko nicht vernachlässigbar, muss es zuerst gemindert werden, bevor die Ware in Verkehr gebracht werden darf.' },
      { badge: '5', title: 'Sorgfaltserklärung in TRACES', text: 'Abgabe im EU-Informationssystem vor dem Inverkehrbringen. Die Funktionsweise hat die Kommission am 13.07.2026 festgelegt.' },
      { badge: '6', title: 'Referenznummern weitergeben', text: 'Die Nummer der Sorgfaltserklärung wird an die nachgelagerten Abnehmer kommuniziert. Ohne sie darf die Ware nicht weiter.' },
    ],
    takeaway: 'Kaffee ist erfasst — neben Kakao, Rind, Palmöl, Kautschuk, Soja und Holz. Für Kaffee kamen 2026 weitere Erzeugnisse hinzu.',
    source: 'VO (EU) 2023/1115 i. d. F. VO (EU) 2025/2650 · Kommissionsmaßnahmen 04.05. und 13.07.2026 [recherchiert]',
    notes: [
      'Sechs Pflichten, die zusammen die Sorgfaltspflicht ergeben. Ich hebe drei hervor, weil sie den Aufwand bestimmen.',
      '',
      'Erstens die Geolokation: für jede Parzelle Koordinaten, über vier Hektar ein Polygon. Und hier eine Formulierung, die in der Praxis unterschätzt wird — die Daten müssen einer Satellitenverifikation und einem Behördenaudit standhalten. Ein schlampig erfasstes Polygon, das über eine Straße oder in einen Nachbarwald ragt, erzeugt einen Risikotreffer, den wir dann aufwendig widerlegen müssen.',
      '',
      'Zweitens der Stichtag, 31. Dezember 2020. Alles, was danach entwaldet wurde, ist nicht marktfähig — unabhängig davon, ob es im Erzeugerland legal war.',
      '',
      'Am Ende steht die Sorgfaltserklärung in TRACES und die Weitergabe der Referenznummer. Ohne diese Nummer darf die Ware nicht weiter — sie ist betriebswirtschaftlich so kritisch wie ein Zolldokument.',
    ].join('\n'),
  },
  {
    layout: 'timeline',
    kicker: 'Fristen nach der Revision',
    title: 'Verordnung (EU) 2025/2650 — zweimal verschoben, jetzt steht sie',
    speaker: 2,
    phases: [
      { num: '1', title: 'Ursprünglich', when: '30.12.2024', text: 'Der erste geplante Anwendungsbeginn. Wurde nach massiver Kritik von Wirtschaft und Drittländern verschoben.' },
      { num: '2', title: 'Erste Verschiebung', when: '30.12.2025', text: 'Auch dieses Datum fiel. Im Dezember 2025 beschlossen Rat und Parlament eine gezielte Revision mit erneuter Verschiebung.' },
      { num: '3', title: 'Gültig für uns', when: '30.12.2026', text: 'Große und mittlere Unternehmen sowie Kleinstunternehmen im Holzsektor. Unser Fallunternehmen fällt hierunter.', emph: true },
      { num: '4', title: 'Kleinunternehmen', when: '30.06.2027', text: 'Übrige Kleinst- und Kleinunternehmen. Für unsere Rösterei nicht relevant — sie ist zu groß.' },
    ],
    takeaway: 'Am 04.05.2026 hat die Kommission signalisiert, dass der Verordnungstext nicht erneut geöffnet wird. Planung ohne Verschiebungspuffer.',
    source: 'VO (EU) 2025/2650, EUR-Lex · Rat der EU, 18.12.2025 · Kommissionspaket 04.05.2026 [recherchiert]',
    notes: [
      'Diese Folie ist der Grund, warum wir bei der Recherche so vorsichtig waren.',
      '',
      'Die Verordnung sollte ursprünglich Ende 2024 gelten. Das Datum fiel. Dann Ende 2025 — fiel auch. Im Dezember 2025 beschlossen Rat und Parlament die Revision 2025/2650 mit einer weiteren Verschiebung um ein Jahr.',
      '',
      'Jetzt gilt: Ende Dezember 2026 für große und mittlere Unternehmen, Mitte 2027 für die übrigen Kleinen. Unser Fallunternehmen ist zu groß für die Ausnahme.',
      '',
      'Unsere Empfehlung ist deshalb eindeutig: ohne Verschiebungspuffer planen. Wer auf eine dritte Verschiebung wettet und verliert, darf seine Ware nicht verkaufen.',
    ].join('\n'),
  },
  {
    layout: 'compare',
    kicker: 'Die wichtigste Vereinfachung',
    title: 'Primärbetreiber oder nachgelagert — ein gewaltiger Unterschied',
    speaker: 2,
    columns: [
      {
        head: 'Primärbetreiber', sub: 'bringt zuerst in Verkehr oder führt aus',
        highlight: true,
        rows: [
          'Volle Sorgfaltspflicht',
          'Geolokation aller Erzeugerparzellen selbst beschaffen',
          'Risikobewertung und Risikominderung dokumentieren',
          'Eigene Sorgfaltserklärung in TRACES einreichen',
          'Referenznummer an Abnehmer weitergeben',
          '= Hoher Aufwand, hohes Haftungsrisiko',
        ],
      },
      {
        head: 'Downstream-Betreiber / -Händler', sub: 'alle nachgelagerten Akteure',
        rows: [
          'Keine eigene Sorgfaltserklärung mehr',
          'Keine eigene Geodatenerhebung',
          'Nur der erste nachgelagerte Akteur muss die Referenznummer aufbewahren',
          '… und sie an seine Abnehmer weitergeben',
          '',
          '= Geringer Aufwand — aber Vertragsrisiko',
        ],
      },
    ],
    takeaway: 'Vor der Revision mussten auch nachgelagerte Unternehmen eigene Erklärungen abgeben. Diese Pflicht ist entfallen — die Kommission erwartet rund 75 % geringere Befolgungskosten.',
    source: 'VO (EU) 2025/2650, neue Betreiberdefinitionen [recherchiert]',
    notes: [
      'Das ist die inhaltlich wichtigste Änderung der Revision, und sie entscheidet über den Großteil unseres Projektaufwands.',
      '',
      'Der Primärbetreiber ist derjenige, der zuerst auf den EU-Markt bringt oder ausführt. Er trägt die volle Last: Geodaten aller Parzellen beschaffen, Risiko bewerten, notfalls mindern, eigene Sorgfaltserklärung einreichen, Referenznummer weitergeben.',
      '',
      'Alle nachgelagerten Akteure haben es seit der Revision drastisch leichter. Sie müssen keine eigene Sorgfaltserklärung mehr abgeben. Nur der erste nachgelagerte Akteur muss die Referenznummer aufbewahren und weiterreichen — das ist im Kern Dokumentenverwaltung. Vor der Revision war das anders; die Kommission erwartet dadurch rund fünfundsiebzig Prozent geringere jährliche Befolgungskosten.',
      '',
      'Beachten Sie aber die letzte Zeile rechts: Geringer Aufwand heißt nicht kein Risiko. Es verlagert sich nur — von der Datenbeschaffung auf den Vertrag. Liefert der Importeur die Referenznummer nicht rechtzeitig, dürfen wir die Ware nicht weitergeben. Dann steht die Produktion.',
    ].join('\n'),
  },
  {
    layout: 'decision',
    kicker: 'Anwendung auf unser Fallunternehmen',
    title: 'Die Entscheidung fällt je Lot — nicht je Unternehmen',
    speaker: 2,
    question: 'Wer steht als Anmelder auf der Zollanmeldung bei der Einfuhr in die EU?',
    branches: [
      {
        cond: 'WIR SELBST — Direct-Trade-Lot',
        role: 'Primärbetreiber',
        duties: [
          'Geolokation aller Parzellen beschaffen',
          'Erntezeitraum und Legalitätsnachweise',
          'Risikoprüfung gegen Waldverlustdaten',
          'Sorgfaltserklärung in TRACES abgeben',
          'Referenznummer sichern und weitergeben',
        ],
      },
      {
        cond: 'EU-IMPORTEUR — zugekauftes Lot',
        role: 'Erster Downstream-Betreiber',
        duties: [
          'Referenznummer beim Importeur einholen',
          'Aufbewahren und archivieren',
          'An eigene Abnehmer weitergeben',
          'Vertraglich absichern, mit Frist',
          'Keine eigene Erklärung, keine Geodaten',
        ],
      },
    ],
    takeaway: 'Das Kriterium ist der Zollanmelderstatus — nicht wer verhandelt hat, nicht wer bezahlt, nicht wessen Name auf dem Sack steht.',
    source: 'Rollenzuordnung nach VO (EU) 2025/2650 [recherchiert] · Anwendung auf den Fall [angenommen]',
    notes: [
      'Jetzt wenden wir das auf unser Fallunternehmen an, und hier wird es praktisch.',
      '',
      'Weil die Rösterei in Mischform beschafft, laufen beide Regime parallel. Und — das ist der entscheidende Satz dieser Folie — die Entscheidung fällt je Lot, nicht je Unternehmen. Dasselbe Unternehmen kann bei der Partie im linken Silo Primärbetreiber sein und bei der im rechten nachgelagerter Akteur.',
      '',
      'Und jetzt der Punkt, an dem wir einem verbreiteten Irrtum widersprechen müssen. Das Kriterium ist nicht, wer verhandelt hat, nicht wer bezahlt, nicht wessen Name auf dem Jutesack steht. Auch die Incoterms allein entscheiden es nicht: Eine DDP-Lieferung aus einem Drittland kann bedeuten, dass wir gerade nicht Einführer sind — ein FOB-Einkauf über einen europäischen Agenten, dass wir es sehr wohl sind.',
      '',
      'Deshalb ist unsere erste Empfehlung nicht technisch, sondern administrativ: eine Liste aller Bezugsquellen mit Zollanmelderstatus, bestätigt von Zoll und Recht. Ein Tagesprojekt, das über den halben Umsetzungsaufwand entscheidet.',
    ].join('\n'),
  },
  {
    layout: 'bullets',
    kicker: 'Ungeklärt',
    title: 'Löst das Rösten ein erneutes Inverkehrbringen aus?',
    speaker: 2,
    bullets: [
      ['Die Zolltarifnummer ändert sich — innerhalb derselben Position',
        'Grünkaffee ist 0901 11, gerösteter Kaffee 0901 21. Beides gehört zur Position 0901. Genau diese Halbheit erzeugt den Streit.'],
      ['Auslegung A: Downstream-Vorgang',
        'Da der Input bereits sorgfaltsgeprüft war, genügt die Weitergabe der Referenznummer. Rösten schafft keine neue Pflicht.'],
      ['Auslegung B: Die Rösterei bleibt Händler',
        'Weil sich die HS-Position nicht ändert, sei die Rösterei kein Verarbeiter, sondern Händler — mit entsprechend anderen Pflichten.'],
      ['Unser Umgang damit: das Datenmodell trägt beide Auslegungen',
        'Wir führen die Verknüpfung Grünkaffee → Röstcharge → verkaufte Einheit immer lückenlos. Die Zusatzkosten sind gering; eine nachträgliche Rekonstruktion wäre teuer.'],
    ],
    aside: {
      label: 'Empfehlung',
      text: 'Rechtsgutachten beauftragen — idealerweise abgestimmt mit dem Kaffeeverband.\n\nEine Branchenposition ist belastbarer als eine Einzelmeinung.',
      size: 14,
    },
    takeaway: 'Wir behaupten hier keine Klarheit, die es nicht gibt. Die Quellenlage ist widersprüchlich — das ist ein Ergebnis, kein Versäumnis.',
    source: 'Quellenlage widersprüchlich: TraceX bzw. European Coffee Federation [recherchiert, uneinheitlich]',
    notes: [
      'Diese Folie zeigt bewusst eine offene Frage als offene Frage. Wir hätten sie glätten können, aber das wäre unredlich gewesen.',
      '',
      'Grünkaffee hat die Zolltarifnummer 0901 11, gerösteter Kaffee 0901 21. Die Nummer ändert sich also — aber beide bleiben in derselben Position 0901. Genau diese Halbheit erzeugt zwei vertretbare Auslegungen.',
      '',
      'Die eine sagt: Weil sich der Code ändert und der Input geprüft war, ist Rösten ein nachgelagerter Vorgang, die Referenznummer genügt. Die andere sagt: Weil die HS-Position gleich bleibt, ist die Rösterei kein Verarbeiter, sondern Händler. Wir haben für beide Auslegungen belastbare Quellen gefunden. Sie widersprechen sich.',
      '',
      'Wie gehen wir damit um? Nicht durch Raten, sondern durch Design. Unser Datenmodell führt die Kette von der Grünkaffeepartie bis zur verkauften Einheit immer lückenlos — auch wenn rechtlich weniger nötig gewesen wäre.',
      '',
      'Unsere Empfehlung rechts: Rechtsgutachten beauftragen, möglichst abgestimmt mit dem Kaffeeverband. Eine Branchenposition ist gegenüber einer Behörde belastbarer als eine Einzelmeinung.',
    ].join('\n'),
  },
  {
    layout: 'statement',
    kicker: 'Befund, der die Aufgabenstellung korrigiert',
    statement: 'Für Kaffee gibt es keine\nDPP-Pflicht. Die Ökodesign-\nVerordnung gilt hier nicht.',
    size: 32,
    points: [
      'Artikel 1 Absatz 2 ESPR nimmt Lebensmittel im Sinne der VO (EG) 178/2002 ausdrücklich vom Anwendungsbereich aus',
      'Der ESPR-Arbeitsplan 2025–2030 priorisiert Stahl, Textilien, Reifen, Aluminium, Möbel und Matratzen — kein Lebensmittel',
      'Damit ist ein Digitaler Produktpass für Röstkaffee freiwilliges Marketing, keine Compliance-Ausgabe',
      'Prüffrage an jeden Anbieter, der Ihnen einen DPP als Pflicht verkauft: Nennen Sie den delegierten Rechtsakt.',
    ],
    source: 'VO (EU) 2024/1781 Art. 1 Abs. 2, EUR-Lex · ESPR-Arbeitsplan vom 16.04.2025 [recherchiert]',
    notes: [
      'Und hier ist der Befund, den mein Kollege angekündigt hat. Er hat einen kompletten Baustein unseres Auftrags gestrichen.',
      '',
      'Die Aufgabenstellung verlangte, den Digitalen Produktpass auszugestalten, wörtlich mit den Pflichtfeldern nach aktuellem ESPR-Stand. Wir haben das am Verordnungstext geprüft. Diese Pflichtfelder existieren nicht.',
      '',
      'Artikel 1 Absatz 2 der Ökodesign-Verordnung nimmt Lebensmittel im Sinne der Verordnung 178/2002 ausdrücklich vom Anwendungsbereich aus. Kaffee ist ein Lebensmittel — also nicht noch nicht erfasst, sondern ausgenommen. Zur Gegenprobe der ESPR-Arbeitsplan vom April 2025: Stahl, Textilien, Reifen, Aluminium, Möbel, Matratzen. Kein Lebensmittel, bis 2030 nicht.',
      '',
      'Was folgt daraus? Ein Produktpass kann trotzdem sinnvoll sein — als Vertriebsinstrument, als Träger der Nachweiskette, als Rückrufwerkzeug. Aber er ist eine Investitionsentscheidung und muss sich als solche rechtfertigen. Er ist kein Compliance-Budget, und er hat keine Frist.',
      '',
      'Der letzte Punkt ist unsere praktische Empfehlung, und sie ist prüfbar: Wenn ein Anbieter Ihnen einen Produktpass als ESPR-Compliance verkauft, verlangen Sie die Nennung des delegierten Rechtsakts. Es gibt keinen.',
    ].join('\n'),
  },
  {
    layout: 'timeline',
    kicker: 'Was bei der Verpackung wirklich Pflicht wird',
    title: 'PPWR — Verordnung (EU) 2025/40',
    speaker: 2,
    phases: [
      { num: '1', title: 'Grundpflichten', when: 'seit 12.08.2026', text: 'Konformitätserklärung und technische Dokumentation. Herstelleridentifikation auf der Verpackung, per QR oder in Begleitpapieren. Ausdrücklich kein QR-Zwang.' },
      { num: '2', title: 'Option der Staaten', when: 'ab 12.02.2027', text: 'Mitgliedstaaten können für Verpackungen mit Herstellerverantwortung ein QR-basiertes digitales Label vorschreiben. Eine Möglichkeit, keine EU-weite Pflicht.' },
      { num: '3', title: 'Harmonisierte Kennzeichnung', when: 'ab 12.08.2028', text: 'Piktogramme zu Material, Sortierung und Verwertbarkeit. Ein Datenträger — QR oder gleichwertig offen — wird Teil des Labels.', emph: true },
      { num: '4', title: 'Was das für uns heißt', when: 'Planungsfolge', text: 'Wenn 2028 ohnehin ein Datenträger auf die Packung muss: ein QR-Code, eine Datenbasis für Pflichtangaben und freiwillige Herkunftsinfos.' },
    ],
    takeaway: 'Aber Vorsicht: Die PPWR verlangt Recycling-Angaben, keinen einzigen Herkunftsdatensatz. Sie ersetzt den DPP nicht, sie ist etwas anderes.',
    source: 'VO (EU) 2025/40, Art. 12 · DIHK-Merkblatt PPWR [recherchiert]',
    notes: [
      'Wenn der Produktpass nicht Pflicht ist — was ist bei der Verpackung dann tatsächlich Pflicht? Das ist die PPWR, gültig seit August 2026.',
      '',
      'Hier ein verbreiteter Irrtum: Seit August 2026 sind Konformitätserklärung, technische Dokumentation und Herstelleridentifikation Pflicht. Was ausdrücklich nicht Pflicht ist: ein QR-Code. Die Identifikation darf auch aufgedruckt sein oder in Begleitpapieren stehen.',
      '',
      'Ab Februar 2027 können einzelne Mitgliedstaaten ein QR-basiertes Label vorschreiben — können, nicht müssen. Verbindlich wird es im August 2028 mit der harmonisierten Kennzeichnung; dann wird ein Datenträger Teil des Labels.',
      '',
      'Daraus folgt die vierte Spalte: Wenn 2028 ohnehin ein Datenträger auf die Packung muss, planen Sie jetzt einen QR-Code und eine Datenbasis für Pflichtangaben und freiwillige Herkunftsinformationen gemeinsam. Zwei Codes und zwei Projekte wären vermeidbare Doppelarbeit.',
      '',
      'Aber verwechseln Sie die beiden Dinge nicht: Die PPWR verlangt Angaben zu Recycling und Entsorgung, keinen einzigen Datensatz zur Herkunft. Sie ersetzt den Produktpass nicht — sie benutzt nur denselben Träger.',
    ].join('\n'),
  },
  {
    layout: 'compare',
    kicker: 'Zertifizierung',
    title: 'Ersetzt Fairtrade die EUDR? Nein — und das ist ein harter Bruch',
    speaker: 2,
    columns: [
      {
        head: 'Zertifizierungs-Massenbilanz', sub: 'Fairtrade, Rainforest Alliance, Bio',
        rows: [
          'Zertifizierte und nicht-zertifizierte Ware darf physisch gemischt werden',
          'Entscheidend ist, dass die Mengenbuchhaltung stimmt',
          'Eine Gutschrift beweist nichts über den Inhalt des konkreten Sacks',
          '= Für EUDR-Zwecke wertlos',
        ],
      },
      {
        head: 'EUDR-Anforderung', sub: 'Verordnung (EU) 2023/1115',
        highlight: true,
        rows: [
          'Geolokation der Parzellen, aus denen die tatsächlich gelieferte Charge stammt',
          'Keine Vermischungslogik, keine Gutschriften',
          'Physische Zuordnung oder dokumentierter Genauigkeitsverlust',
          '= Kein Zertifikat ersetzt die Sorgfaltserklärung',
        ],
      },
    ],
    takeaway: 'Aber: Zertifizierte Ketten sind besser dokumentiert. Fairtrade stellt seit Juni 2026 mit Fairtrace ein kostenloses Geolokationstool für Kooperativen bereit — das ist Ihre günstigste Datenquelle.',
    source: 'Zertifizierungslogik [recherchiert] · Fairtrace: Daily Coffee News, 16.06.2026 [recherchiert]',
    notes: [
      'Letzte Folie meines Blocks, und eine Frage aus der Aufgabenstellung: Wie verhält sich das System zu Fairtrade, Rainforest Alliance und Bio — Ersatz, Ergänzung oder Doppelarbeit? Antwort: Ergänzung, mit einem harten Bruch.',
      '',
      'Der Bruch liegt im Begriff Massenbilanz, der in beiden Welten vorkommt und Verschiedenes bedeutet. Die Zertifizierer erlauben, zertifizierte und nicht-zertifizierte Ware zu mischen, solange die Mengenbuchhaltung stimmt. Genau das ist für die EUDR wertlos: Sie will die Koordinaten der Parzellen, aus denen die tatsächlich gelieferte Charge stammt. Eine Gutschrift beweist nichts über den Inhalt des Sacks. Kein Zertifikat ersetzt die Sorgfaltserklärung.',
      '',
      'Die gute Nachricht unten: Zertifizierte Ketten sind besser dokumentiert und leichter auf Parzellenebene aufzulösen. Der Zertifizierungsstatus sagt also viel darüber, wie leicht Sie an Geodaten kommen — nur nichts über die Konformität selbst.',
      '',
      'Und Fairtrade hat nachgelegt: seit Juni 2026 mit Fairtrace ein kostenloses Geolokationswerkzeug für Kooperativen. Wer eine kommerzielle Kartierung beauftragt, ohne das vorher zu prüfen, verbrennt Geld.',
      '',
      'Damit übergebe ich an den dritten Block.',
    ].join('\n'),
  },
];

module.exports = { BLOCK_B };
