/** Inhalt Teil 3 — Block C: Kette und Daten (Sprecher:in 3), Block D: Architektur und Bilanz (Sprecher:in 4). */

const BLOCK_C = [
  {
    layout: 'divider',
    num: 'C',
    title: 'Lieferkette und Datenmodell',
    subtitle: 'Wer liefert welche Daten, wo reißt die Kette —\nund was davon darf unveränderlich gespeichert werden?',
    speaker: 3,
    minutes: 10,
    notes: [
      'Danke. In meinem Block geht es um die Frage, die über Erfolg und Scheitern entscheidet und die in Technikprojekten regelmäßig zu spät gestellt wird: Wer liefert eigentlich die Daten?',
      'Ich zeige Ihnen die Kette und ihre Bruchstellen, dann das Datenmodell, dann den Datenschutzkonflikt und zum Schluss zwei Konzepte, die wir für besonders wertvoll halten.',
    ].join(' '),
  },
  {
    layout: 'flow',
    kicker: 'Die Kette, ehrlich gezeichnet',
    title: 'Vom Kleinbauern zur Rösterei — und wo es reißt',
    speaker: 3,
    steps: [
      { title: 'Kleinbauer', text: 'Parzelle, Ernte.\nVertrauensanker: schwach' },
      { title: 'Kooperative', text: 'Erntecharge, Polygonerfassung.\nAnker: mittel, Institution', emph: true },
      { title: 'Trockenmühle & Exporteur', text: 'Exportlot, Dokumente.\nAnker: mittel' },
      { title: 'Importeur', text: 'Nur bei Zukauf.\nLiefert die Referenznummer' },
      { title: 'Rösterei', text: 'Röstung, Blend, Abpackung.\nAnker: stark, eigene Geräte', emph: true },
    ],
    breaks: {
      label: 'Die vier Bruchstellen — nach absteigender Wahrscheinlichkeit',
      items: [
        '1 · Trockenmühle: mehrere Kooperativen in einem Verarbeitungslauf',
        '2 · Sammelstelle: Kleinbauern liefern in gemeinsame Behälter',
        '3 · Unser Blend: n Herkünfte in einer Verkaufseinheit',
        '4 · Unser Silo: Restbestände mehrerer Partien ohne FIFO-Disziplin',
      ],
    },
    takeaway: 'Der zentrale Satz: Keine dieser vier Bruchstellen wird durch einen Ledger repariert. Eine Blockchain macht sie nur unveränderlich dokumentiert.',
    source: 'Kettenstruktur und Bruchstellen [angenommen, branchenüblich]',
    notes: [
      'Das ist die Kette, ehrlich gezeichnet. Unter jeder Station steht, wie belastbar der Vertrauensanker dort ist.',
      '',
      'Wichtiger ist die rote Zeile unten: die vier Stellen, an denen die Kette in der Praxis reißt.',
      '',
      'Bruchstelle eins ist die Trockenmühle, wo Chargen mehrerer Kooperativen in einem Verarbeitungslauf zusammenlaufen. Ab dort ist die Zuordnung zu einer Parzelle nur noch statistisch. Das ist die folgenschwerste Bruchstelle, und sie liegt außerhalb unseres Einflusses: Getrennte Verarbeitungsläufe kosten den Exporteur echtes Geld — man muss sie vertraglich verlangen und bezahlen.',
      '',
      'Bruchstelle zwei ist die Sammelstelle der Kooperative. Die Bruchstellen drei und vier erzeugen wir selbst: unseren Blend und Restbestände mehrerer Partien im selben Silo. Ohne FIFO-Disziplin ist die Zuordnung dort schlicht erfunden.',
      '',
      'Und jetzt der Satz, der für den ganzen Vortrag zentral ist: Keine dieser vier Bruchstellen wird durch einen Ledger repariert. Eine Blockchain macht sie nur unveränderlich dokumentiert. Das ist etwas völlig anderes.',
    ].join('\n'),
  },
  {
    layout: 'cards',
    kicker: 'Anreize und Widerstände',
    title: 'Warum Akteure mitmachen — oder eben nicht',
    speaker: 3,
    cols: 3,
    cards: [
      { badge: '1', title: 'Kleinbauer', text: 'Anreiz: Marktzugang — ohne Daten kein Verkauf nach Europa. Das ist ein Zwang, kein Angebot.\n\nWiderstand: kein Smartphone, teils keine formalen Landtitel, berechtigte Sorge vor Weitergabe an Steuer- und Behörden.' },
      { badge: '2', title: 'Kooperative', tone: 'good', text: 'Anreiz: existenziell — die EUDR-Fähigkeit entscheidet über die Absatzfähigkeit der gesamten Mitgliederernte.\n\nWiderstand: Kosten der Kartierung, und fünf Käufer, die fünf verschiedene Formate verlangen.' },
      { badge: '3', title: 'Exporteur', text: 'Anreiz: hoch, er verliert sonst den EU-Absatz.\n\nWiderstand: Rückverfolgbarkeit bis zur Parzelle heißt getrennte Verarbeitungsläufe — und damit echte Zusatzkosten in der Trockenmühle.' },
      { badge: '4', title: 'Importeur', text: 'Anreiz: er ist selbst Primärbetreiber und trägt das Risiko.\n\nWiderstand: Er schützt seine Bezugsquellen. Er gibt uns die Referenznummer — die Parzellendaten dahinter nicht. Das ist legitim und ausreichend.' },
      { badge: '5', title: 'Unsere Röstmannschaft', tone: 'bad', text: 'Anreiz: gering. Für sie ist es Zusatzarbeit.\n\nWiderstand: Jede zusätzliche Minute je Charge wird umgangen, sobald der Betrieb hektisch wird. Das ist das häufigste Scheiterkriterium — nicht die Technik.' },
      { badge: '6', title: 'B2B-Kunde', text: 'Anreiz: eigene Compliance und die eigene Scope-3-Bilanz.\n\nDer einzige Akteur in der ganzen Kette, der für Verifizierbarkeit tatsächlich zahlen könnte. Ob er es tut, ist unsere offene Kernfrage.' },
    ],
    source: 'Akteursanalyse [angenommen, aus Branchenpraxis abgeleitet]',
    notes: [
      'Zu jedem Akteur gehört ein Anreiz und ein Widerstand. Ich greife drei heraus.',
      '',
      'Beim Kleinbauern ist der Anreiz Marktzugang — und man sollte ehrlich sein: Das ist ein Zwang, kein Angebot. Der Widerstand ist teilweise berechtigt: kein Smartphone, oft keine formalen Landtitel, und die begründete Sorge, dass GPS-Daten bei der Steuerverwaltung landen.',
      '',
      'Bei der Kooperative ist der Anreiz existenziell, und trotzdem gibt es Widerstand. Der Hauptärger im Feld ist nicht die Kartierung an sich, sondern dass fünf Käufer fünf verschiedene Datenformate verlangen. Daraus folgt eine unserer wichtigsten Architekturregeln: so wenig Formatzwang wie möglich. Jede Anforderung, die eine Kooperative zwingt, ein sechstes System zu bedienen, erhöht das Risiko, dass sie gar nicht liefert.',
      '',
      'Und dann Karte fünf, rot markiert, weil sie in Präsentationen wie dieser fast immer fehlt: unsere eigene Röstmannschaft. Für sie ist das Ganze Zusatzarbeit ohne erkennbaren eigenen Nutzen. Das ist nach unserer Einschätzung das häufigste Scheiterkriterium solcher Projekte — nicht die Technik, nicht die Regulatorik, sondern die Erfassungsdisziplin am dritten Tag der Hochsaison.',
      '',
      'Die Konsequenz für den Entwurf: Erfassung muss aus Handlungen fallen, die ohnehin stattfinden — die Waage, das Röstprotokoll — und darf nicht zusätzlich sein.',
    ].join('\n'),
  },
  {
    layout: 'bullets',
    kicker: 'Datenmodell',
    title: 'GS1 EPCIS 2.0 statt Eigenformat',
    speaker: 3,
    bullets: [
      ['Der Standard bildet genau ab, was wir brauchen',
        'Ereignisse mit „was, wann, wo, warum", dazu Aggregation — Sack zu Palette — und Transformation, also Grünkaffee zu Röstkaffee. Version 2.0 spricht REST und JSON statt SOAP.'],
      ['Für die EUDR existiert bereits eine Umsetzungshilfe',
        'GS1 Germany hat eine EUDR-Implementierungsrichtlinie veröffentlicht; der GS1-EUDR-Standard referenziert EPCIS als Mechanismus zur Übermittlung von Referenz- und Verifikationsnummern.'],
      ['Unsere Handelspartner sprechen ohnehin GS1',
        'GTIN, GLN und SSCC sind im Lebensmitteleinzelhandel gesetzt. Ein Eigenformat müssten wir an jeder Schnittstelle übersetzen.'],
      ['Die ehrliche Einschränkung: nicht bis zum Feld',
        'Kooperativen werden kein EPCIS senden. Upstream nehmen wir CSV, GeoJSON und Excel entgegen; EPCIS ist unser internes Modell ab Wareneingang.'],
    ],
    aside: {
      label: 'Entitäten',
      text: 'Parzelle\nErntecharge\nExportlot\nGrünkaffeepartie\nRöstcharge\nBlend\nVerpackungseinheit',
      size: 15,
    },
    takeaway: 'Grundregel: Jede Entität hat genau einen verantwortlichen Erfasser und genau einen Erfassungszeitstempel. Ohne diese zwei Felder funktioniert das Evidence Grading nicht.',
    source: 'GS1 EPCIS 2.0 · GS1 Germany EUDR Implementation Guideline v1.11 [recherchiert]',
    notes: [
      'Die Aufgabenstellung hat uns ausdrücklich gefragt, ob GS1 EPCIS 2.0 passt, statt ein Eigenformat zu erfinden. Unsere Antwort: ja, mit einer Einschränkung.',
      '',
      'EPCIS bildet genau die Ereignistypen ab, die wir brauchen: Objektereignisse für Wareneingang und Versand, Aggregation für Säcke auf einer Palette, und Transformation — unser Kernfall, denn Rösten und Blenden sind Transformationen mit Masseverlust.',
      '',
      'Jetzt die Einschränkung: EPCIS ist für den Feldbereich zu schwergewichtig. Eine Kooperative in Äthiopien wird uns niemals EPCIS senden. Deshalb ist unsere Umsetzung zweigeteilt — upstream nehmen wir entgegen, was kommt, und EPCIS ist unser internes Modell ab Wareneingang. Wer EPCIS bis zum Kleinbauern durchdrücken will, blockiert das Projekt.',
      '',
      'Unten die Grundregel, die alles zusammenhält: Jede Entität hat genau einen verantwortlichen Erfasser und genau einen Erfassungszeitstempel. Ohne diese beiden Felder funktioniert das Evidence Grading nicht.',
    ].join('\n'),
  },
  {
    layout: 'cards',
    kicker: 'Datenschutz',
    title: 'Der Konflikt: Löschrecht gegen Unveränderlichkeit',
    speaker: 3,
    cols: 3,
    cards: [
      { badge: '1', title: 'Off-chain, zugriffsbeschränkt', tone: 'good', text: 'Parzellengeometrien, Erzeugernamen, Landtitel, Verträge, Preise, alle Dokumente.\n\nVollständig löschbar. DSGVO-konform.' },
      { badge: '2', title: 'Off-chain, veröffentlicht', text: 'Land, Region, Kooperative, Höhenlage, Varietät, Aufbereitung, Erntejahr.\n\nNiemals Parzellengeometrie. Niemals Erzeugername.' },
      { badge: '3', title: 'Verankert — nur Hashes', tone: 'bad', text: 'Nie ein Dokument, nie eine Koordinate, nie ein Name, nie ein Pseudonym mit Wiedererkennungswert.\n\nNicht löschbar — deshalb Karte 4 bis 6.' },
      { badge: '4', title: 'Das Problem mit blanken Hashes', text: 'Ein Hash über eine Koordinate ist nicht anonym. Der Suchraum von Koordinaten ist klein genug, um ihn per Brute Force zu durchsuchen.' },
      { badge: '5', title: 'Die Lösung: Crypto-Shredding', tone: 'good', text: 'Je Datensatz ein zufälliges Salt, ausschließlich off-chain gespeichert. Verankert wird der Hash aus Salt plus Datensatz.' },
      { badge: '6', title: 'Beim Löschverlangen', text: 'Datensatz und Salt werden gelöscht. Zurück bleibt ein Hash, der ohne Salt nicht mehr rückführbar ist. Die Prüfbarkeit dieses Datensatzes ist dauerhaft verloren — das ist der Preis.' },
    ],
    takeaway: 'Solange wir nicht verankern, existiert dieser Konflikt gar nicht. Ein weiterer Grund, die Blockchain nicht vorzuziehen.',
    source: 'Einordnung als personenbezogenes Datum [angenommen, vorsichtige Auslegung] · Crypto-Shredding etabliert, aber nicht höchstrichterlich bestätigt',
    notes: [
      'Jetzt der Datenschutzkonflikt, den die Aufgabenstellung aufgeworfen hat — und den der Referenzfall nicht sichtbar auflöst.',
      '',
      'Wir gehen davon aus, dass Parzellenkoordinaten personenbeziehbare Daten sind, weil jede Parzelle einen Bewirtschafter hat. Damit greift die Datenschutzgrundverordnung samt Löschrecht. Gleichzeitig verlangt die EUDR, genau diese Koordinaten zu übermitteln. Der Konflikt ist also nicht ob man darf — man muss —, sondern: Was davon darf in ein unveränderliches System?',
      '',
      'Unsere Antwort sind drei Zonen. In der geschützten Zone liegt alles Sensible, vollständig löschbar. In der veröffentlichten Zone stehen Land, Region, Kooperative, Höhe und Varietät — aber niemals eine Geometrie und niemals ein Erzeugername. In der verankerten Zone liegen ausschließlich Hashes. Diese Regel ist nicht verhandelbar: Ein einziges personenbezogenes Datum in einem unveränderlichen Ledger ist ein dauerhafter, nicht heilbarer Verstoß.',
      '',
      'Die Lösung heißt Crypto-Shredding: je Datensatz ein zufälliges Salt, ausschließlich off-chain gespeichert, verankert wird der Hash aus Salt plus Datensatz. Beim Löschverlangen löschen wir beides. Zurück bleibt ein Hash, der ohne Salt nicht mehr rückführbar ist.',
      '',
      'Der Preis steht auf Karte sechs, und wir nennen ihn offen: Die Prüfbarkeit dieses Datensatzes ist danach dauerhaft verloren. Die Konstruktion ist etabliert, aber nicht höchstrichterlich bestätigt.',
      '',
      'Der pragmatische Schluss unten: Solange wir nicht verankern, existiert dieser ganze Konflikt gar nicht.',
    ].join('\n'),
  },
  {
    layout: 'compare',
    kicker: 'Aus dem Referenzfall übernommen',
    title: 'Evidence Grading — schwache Daten kennzeichnen statt ablehnen',
    speaker: 3,
    columns: [
      {
        head: 'Verified', sub: 'zeitgleich, signiert, unverändert',
        highlight: true,
        rows: [
          'Ereigniszeit und Erfassungszeit liegen unter 15 Minuten auseinander',
          'Identifizierter Erfasser mit gültigem Schlüssel — gültig zum Ereigniszeitpunkt',
          'Wert kommt aus einem angebundenen Gerät, nicht aus einem Freitextfeld',
          'Keine nachträgliche Korrektur',
          '= Beispiel: die Auswaage einer Röstcharge',
        ],
      },
      {
        head: 'Declared', sub: 'erklärt, aber nicht zeitgleich erfasst',
        rows: [
          'Von einer benannten Partei erklärt',
          'Nicht zeitgleich erfasst oder nicht vom Handelnden selbst signiert',
          'Stellvertretende Erfassung fällt immer hierunter',
          'Eine Korrektur stuft von Verified auf Declared herab',
          '= Beispiel: die Parzellendaten der Kooperative',
        ],
      },
    ],
    takeaway: 'Aggregationsregel: Die Kette ist so stark wie ihr schwächstes Glied — und das schwächste Glied wird benannt. Keine Prozentzahl, kein Trust Score.',
    source: 'Konzept aus dem Kakao-Piloten übernommen, Regeln von uns ausformuliert',
    notes: [
      'Das Evidence Grading ist für uns der wertvollste Baustein des Referenzfalls. Die Grundidee: Schwächere Daten werden nicht abgelehnt, sondern gekennzeichnet. Das verhindert zwei typische Fehler — entweder gar keine Kette zu haben, weil man Perfektion verlangt, oder eine perfekt aussehende Kette zu haben, deren Schwachstellen unsichtbar sind.',
      '',
      'Wir haben die Regeln so ausformuliert, dass eine Maschine sie prüfen kann. Verified ist ein Datenpunkt nur, wenn alle vier Bedingungen links erfüllt sind: Zeitgleichheit unter fünfzehn Minuten, identifizierter Erfasser mit einem zum Ereigniszeitpunkt gültigen Schlüssel, der Wert kommt aus einem angebundenen Gerät statt aus einem Freitextfeld, und es gab keine nachträgliche Korrektur. Fällt eine Bedingung, fällt die Stufe — und eine Aufwertung ist nachträglich nicht möglich.',
      '',
      'Die Aggregationsregel unten ist die Detailfrage, an der solche Systeme kippen. Unsere Antwort: Die Kette ist so stark wie ihr schwächstes Glied, und das schwächste Glied wird benannt. Keine Punktzahl, kein Trust Score. Denn eine Prozentzahl lädt dazu ein, die schwache Stelle wegzumitteln — und die schwache Stelle ist bei Kaffee immer die Herkunftsangabe.',
      '',
      'Was das bedeutet, ist unbequem, und wir sagen es offen: Bei einer typischen Kaffeekette bleibt die Herkunftsangabe — der werblich wichtigste Datenpunkt — dauerhaft Declared. Wer das nicht aushält, sollte das Evidence Grading gar nicht einführen. Denn seine einzige Funktion ist, genau das sichtbar zu machen.',
    ].join('\n'),
  },
  {
    layout: 'cards',
    kicker: 'Identität',
    title: 'DIDs für alle? Nein — abgestuft nach Realität',
    speaker: 3,
    cols: 3,
    cards: [
      { badge: '1', title: 'Rösterei, Geräte, Mitarbeitende', tone: 'good', text: 'Volle Signatur. Schlüssel auf Firmengeräten, Erfassung signiert, vertrauenswürdiger Zeitstempel.\n\n→ Stufe Verified. Hier ist Kryptografie sinnvoll und billig, weil wir die Geräte kontrollieren.' },
      { badge: '2', title: 'Exporteur, Importeur, größere Kooperative', text: 'Signatur möglich, wenn vertraglich vereinbart. Einfachstes tragfähiges Mittel: ein Schlüssel je Organisation, nicht je Person.\n\n→ Vertragsdurchsetzung wirkt hier stärker als Technik.' },
      { badge: '3', title: 'Kleinbauer ohne Smartphone', tone: 'bad', text: 'Keine eigene Signatur. Stellvertretende Erfassung durch die Kooperative, gekennzeichnet als „erfasst durch X am Y".\n\n→ Stufe Declared. Alles andere wäre Fiktion.' },
    ],
    takeaway: 'Der Satz, der im Referenzfall fehlt: Stellvertretende Erfassung verschiebt den Vertrauensanker von der Person auf die Institution — sie schafft ihn nicht.',
    source: 'Widerrufslogik: Sperrliste je Organisationsschlüssel, geprüft zum Ereigniszeitpunkt',
    notes: [
      'Letzte Folie meines Blocks. Der Referenzfall vergibt digitale Identitäten an Personen, Prozesse und Geräte. Wir differenzieren das nach Akteursklasse, sonst wird es Theater.',
      '',
      'Für unsere eigene Rösterei, unsere Geräte und Mitarbeitenden: volle Signatur. Das ist sinnvoll und billig, weil wir die Geräte kontrollieren — hier ist die Stufe Verified tatsächlich erreichbar.',
      '',
      'Für Exporteure, Importeure und größere Kooperativen ist eine Signatur möglich, wenn man sie vertraglich vereinbart. Wir empfehlen aber das einfachste tragfähige Mittel: einen Schlüssel je Organisation, nicht je Person. Ehrlich gesagt wirkt hier ein durchsetzbarer Vertrag stärker als jede Technik.',
      '',
      'Für den Kleinbauern ohne Smartphone: keine eigene Signatur, sondern stellvertretende Erfassung durch die Kooperative, klar gekennzeichnet. Alles andere wäre Fiktion.',
      '',
      'Und jetzt der Satz unten, der im Referenzfall so nicht ausgesprochen wird: Stellvertretende Erfassung verschiebt den Vertrauensanker von der Person auf die Institution. Sie schafft ihn nicht. Wenn die Kooperative falsch erfasst, ist das Ergebnis kryptografisch einwandfrei und inhaltlich falsch. Genau deshalb ist die Bezeichnung als Declared nicht Kosmetik, sondern der Kern der Aussage.',
      '',
      'Ein technisches Detail zur Widerrufslogik: Wir führen eine Sperrliste je Organisationsschlüssel und prüfen die Gültigkeit zum Ereigniszeitpunkt, nicht zum Prüfzeitpunkt. Sonst würde ein Schlüsselwechsel rückwirkend die gesamte Historie entwerten.',
      '',
      'Damit übergebe ich an den vierten Block.',
    ].join('\n'),
  },
];

const BLOCK_D = [
  {
    layout: 'divider',
    num: 'D',
    title: 'Architektur und Massenbilanz',
    subtitle: 'Drei Optionen, die Gegenthese zur Blockchain\nund die Mathematik der Röstung',
    speaker: 4,
    minutes: 10,
    notes: [
      'Vielen Dank. Mein Block hat zwei Hälften. In der ersten stelle ich drei Architekturoptionen vor und prüfe die Gegenthese: Braucht es für diese Aufgabe überhaupt eine verteilte Datenbank?',
      'In der zweiten geht es um die Massenbilanz — also darum, wie man Röstverlust und Blends so verbucht, dass daraus kein Einfallstor wird.',
    ].join(' '),
  },
  {
    layout: 'compare',
    kicker: 'Architektur',
    title: 'Drei Optionen, ergebnisoffen bewertet',
    speaker: 4,
    columns: [
      {
        head: 'A · Zukauf', sub: 'Compliance-SaaS plus ERP, kein Ledger',
        rows: [
          'Volle EUDR-Konformität für beide Pfade',
          'Geodaten, Risikoscreening, TRACES, Referenznummern',
          'Kein Chargenmodell über Röstung und Blend, kein CO₂ je Charge, kein Produktpass',
          '6–10 Wochen bis produktiv',
          '= Zwingend. Das ist Phase 0.',
        ],
      },
      {
        head: 'B · Hybrid', sub: 'Zukauf plus schlanker Eigenbau',
        highlight: true,
        rows: [
          'Alles aus A, plus durchgängige Chargenkette',
          'CO₂ je Röstcharge, Evidence Grading, freiwilliger Produktpass',
          'Verankerung wird vorbereitet, aber nicht aktiviert',
          '4–8 Monate nach Phase 0',
          '= Unsere Empfehlung.',
        ],
      },
      {
        head: 'C · Referenzfall-Klon', sub: 'TrackTrace, Hedera, Token, Marker',
        rows: [
          'Alles aus B, plus verteilte Schreibrechte und Token-Ownership',
          'Zusätzlich: Schlüsselverwaltung über Organisationsgrenzen, Partner-Onboarding, Rechtsklärung',
          'Starke Anbieterbindung in einem jungen Markt',
          '12–24 Monate mit Partner-Onboarding',
          '= Heute nicht begründbar.',
        ],
      },
    ],
    source: 'Zeitangaben [geschätzt] · Funktionsumfang aus Anbieterunterlagen [recherchiert]',
    notes: [
      'Wir haben drei Optionen bewertet, bewusst ergebnisoffen — nicht eine Lösung mit zwei Alibi-Alternativen.',
      '',
      'Option A ist reiner Zukauf: eine EUDR-Compliance-Software plus unser bestehendes ERP, kein Ledger. Das erfüllt die Verordnung vollständig für beide Beschaffungspfade. Was es nicht kann: die chargengenaue Verknüpfung über Röstung und Blend, CO₂ je Charge, Produktpass. Entscheidend ist die vierte Zeile: sechs bis zehn Wochen bis produktiv. Das ist die einzige Option, die in die Frist passt — Option A ist deshalb keine Alternative, sondern Phase 0.',
      '',
      'Option B ist unsere Empfehlung: zugekaufte Compliance plus ein schlanker Eigenbau für Datenhaltung, Evidence Grading und Produktpass. Und der Kniff: Die Verankerung wird vorbereitet, aber nicht aktiviert.',
      '',
      'Option C ist der Referenzfall-Klon. Er kann alles, was B kann, plus zwei Dinge: verteilte Schreibrechte für Parteien, die einander misstrauen, und öffentliche Verifizierbarkeit. Er kostet dafür Schlüsselverwaltung über Organisationsgrenzen hinweg, Partner-Onboarding, Rechtsklärung — und zwölf bis vierundzwanzig Monate.',
      '',
      'Unser Urteil zu C: heute nicht begründbar. Nicht weil die Technik schlecht wäre, sondern weil der Nachfrager fehlt. Warum wir das so hart sagen, zeigt die nächste Folie.',
    ].join('\n'),
  },
  {
    layout: 'bullets',
    kicker: 'Die Gegenthese, ernsthaft geprüft',
    title: 'Reicht eine signierte Datenbank mit Zeitstempel?',
    speaker: 4,
    bullets: [
      ['Zeitgleichheitsnachweis — brauchen wir. Geht ohne Chain.',
        'Merkle-Root je Tag plus qualifizierter eIDAS-Zeitstempel. Vor einem EU-Gericht hat ein qualifizierter Zeitstempel höhere Beweiskraft als eine Chain-Transaktion.'],
      ['Manipulationsschutz gegen uns selbst — brauchen wir. Geht ohne Chain.',
        'Append-only-Datenhaltung, externer Zeitstempel, Testat der Kontrollen durch einen Wirtschaftsprüfer.'],
      ['Schreibrechte für misstrauische Dritte — brauchen wir nicht.',
        'Wir sind der einzige Schreiber. Alle anderen liefern uns Daten. Genau hier läge der Vorteil einer Chain — und er bleibt bei uns ungenutzt.'],
      ['Öffentliche Verifizierbarkeit ohne uns — fragt heute niemand nach.',
        'Das ist die offene Frage an die Geschäftsführung, nicht an die IT.'],
    ],
    aside: {
      label: 'Unser Ergebnis',
      text: 'Merkle-Root immer bilden.\n\nVerankerungsziel austauschbar halten.\n\nDer Wechsel auf Hedera ist dann Konfiguration, kein Umbau.',
      size: 14,
    },
    takeaway: 'Empfehlung Phase 1: Tages-Merkle-Root, qualifizierter eIDAS-Zeitstempel, zusätzlich kostenlos OpenTimestamps. Latenz bis 24 Stunden — für den EUDR-Nachweis völlig ausreichend.',
    notes: [
      'Das ist die Folie, auf die es in meinem Block ankommt. Die Aufgabenstellung hat uns aufgefordert, die Gegenthese zu prüfen: Reicht eine signierte, extern testierte Datenbank mit Merkle-Baum und regelmäßigem Timestamping? Wir haben das ernsthaft geprüft, und die Antwort lautet für unseren Fall: ja.',
      '',
      'Dazu muss man fragen, was ein Ledger eigentlich leistet. Erstens beweist er, dass ein Datensatz zu einem Zeitpunkt existierte. Zweitens erlaubt er mehreren Parteien, die einander nicht vertrauen, in denselben Bestand zu schreiben.',
      '',
      'Jetzt die vier Eigenschaften. Zeitgleichheitsnachweis: Den brauchen wir, das ist der Kern des EUDR-Nachweises. Aber er geht ohne Chain — ein Merkle-Root pro Tag plus ein qualifizierter Zeitstempel nach eIDAS. Und hier ein oft übersehenes Argument: Vor einem europäischen Gericht hat ein qualifizierter Zeitstempel höhere Beweiskraft als eine Chain-Transaktion, weil er rechtlich geregelt ist.',
      '',
      'Manipulationsschutz gegen uns selbst: brauchen wir, geht ebenfalls ohne Chain — Append-only plus externer Zeitstempel plus ein Prüfertestat.',
      '',
      'Schreibrechte für misstrauische Dritte: Das ist der eigentliche Vorteil einer Chain. Und wir brauchen ihn nicht, denn wir sind der einzige Schreiber. Öffentliche Verifizierbarkeit fragt heute niemand nach — und das ist keine IT-Frage, sondern eine an die Geschäftsführung.',
      '',
      'Rechts unser konstruktiver Vorschlag: Wir bilden den Merkle-Root immer und halten das Verankerungsziel austauschbar. Der spätere Wechsel auf Hedera ist dann eine Konfigurationsänderung, kein Umbau.',
    ].join('\n'),
  },
  {
    layout: 'stats',
    kicker: 'Damit das Argument nicht missbraucht wird',
    title: '„Blockchain ist zu teuer" — stimmt bei uns nicht',
    speaker: 4,
    stats: [
      { value: '0,0008 $', label: 'je Nachricht', sub: 'Hedera Consensus Service, fixer USD-Preis seit Januar 2026 — zuvor 0,0001 $', size: 34 },
      { value: '~400 $', label: 'pro Jahr', sub: 'Wenn wir jedes einzelne Ereignis verankern: rund 500.000 Nachrichten im Jahr', size: 38 },
      { value: '~0,30 $', label: 'pro Jahr', sub: 'Wenn wir nur einen Merkle-Root je Tag verankern: 365 Nachrichten', size: 38 },
    ],
    note: 'Wer sagt, Blockchain sei zu teuer, hat nicht gerechnet. Und wer sie mit den niedrigen Transaktionskosten verkauft, argumentiert an der Kostenstruktur vorbei: Bei Option C liegen über 99 % der Kosten in Lizenz, Integration, Partner-Onboarding und Betrieb.',
    takeaway: 'Das stärkste Sachargument gegen Option C ist nicht der Preis, sondern die Anbieterbindung — ein Wechsel entwertet die verankerte Historie.',
    source: 'Hedera Blog, Preisänderung Januar 2026 [recherchiert] · Mengengerüst [geschätzt]',
    notes: [
      'Hedera hat den Preis je Nachricht zum Januar 2026 um den Faktor acht angehoben, von einem Zehntausendstel auf acht Zehntausendstel Dollar. Klingt nach viel. Rechnen wir es um: Bei tausend Tonnen und sechzig Kilogramm je Charge kommen wir auf rund siebzehntausend Röstchargen, dazu Blend-, Pack- und Wareneingangsereignisse. Nehmen wir großzügig fünfhunderttausend Ereignisse im Jahr und verankern jedes einzelne: rund vierhundert Dollar. Verankern wir nur einen Merkle-Root pro Tag, sind es dreißig Cent.',
      '',
      'Daraus folgen zwei Dinge. Erstens: Wer sagt, Blockchain sei zu teuer, hat bei diesem Volumen nicht gerechnet. Zweitens, in der anderen Richtung: Wer Ihnen Option C mit den niedrigen Transaktionskosten verkauft, argumentiert an der Kostenstruktur vorbei. Bei Option C liegen über neunundneunzig Prozent der Kosten in Lizenz, Integration, Onboarding und Betrieb. Die Gebühren sind Rauschen.',
      '',
      'Deshalb steht unten unser eigentliches Gegenargument: Das stärkste Sachargument gegen Option C ist nicht der Preis, sondern die Anbieterbindung. Plattform, Ledger, Token-Modell und Identitätssystem stecken beim selben Anbieter — und ein Wechsel entwertet die bereits verankerte Historie.',
    ].join('\n'),
  },
  {
    layout: 'cards',
    kicker: 'Begründete Streichungen',
    title: 'Was wir aus dem Referenzfall entfernen — und warum',
    speaker: 4,
    cols: 3,
    cards: [
      { badge: '✕', title: 'Physische Marker für Grünkaffee', tone: 'bad', text: 'Jutesäcke werden umgepackt; der Marker sagt nichts über den Inhalt. Und unser Problem ist Herkunftsnachweis, nicht Produktfälschung.\n\nStattdessen: manipulationssichere Siegel plus Stabilisotopen-Stichprobe im Labor — der einzige Ansatz, der den Kaffee selbst prüft.' },
      { badge: '✕', title: 'Token-Ownership für Endkunden', tone: 'bad', text: 'Kein Kaffeekäufer möchte Eigentümer eines Tokens werden.\n\nErzeugt zusätzlich wertpapier- und geldwäscherechtliche Fragen, die man ohne Not nicht aufwirft. Die Massenbilanz-Logik behalten wir — sie braucht keine Chain.' },
      { badge: '✕', title: 'Workflow-Engine und Enterprise-SSO', tone: 'bad', text: 'Unsere Prozesse sind linear und wenige; eine BPMN-Engine erzeugt Modellierungsaufwand ohne Gegenwert.\n\nBei unter hundert internen Nutzenden reicht die Rechteverwaltung von ERP und Compliance-Software. Ein zusätzlicher Identitätsdienst ist eine zusätzliche Ausfallquelle.' },
    ],
    takeaway: 'Ersparnis der Streichungen: rund 165.000 bis 490.000 € einmalig. Der Nutzenverlust in einem Satz — wir können Dritten die Zeitgleichheit nicht ohne unser Zutun beweisen. Danach fragt heute niemand.',
    source: 'Kostenwirkung [geschätzt] · Bewertung der Marker-Alternativen [angenommen]',
    notes: [
      'Erstens die physischen Sicherheitsmarker. Bei Grünkaffee scheitern sie praktisch: Jutesäcke werden unterwegs umgepackt, und ein Marker auf dem Sack sagt nichts über den Inhalt. Auf der Endverbraucherpackung wären sie machbar — aber sie lösen Produktfälschung, und das ist nicht unser Problem. Ein Kaffeefälscher fälscht nicht unsere Tüte; er verkauft billigeren Kaffee als teuren.',
      '',
      'Was wir stattdessen empfehlen: manipulationssichere Siegel mit fortlaufenden Nummern, die im Ereignis erfasst werden — das beweist Unversehrtheit zwischen zwei Punkten und kostet fast nichts. Und eine Stabilisotopen-Analyse als Stichprobe. Das ist der einzige Ansatz, der die Herkunft am Kaffee selbst prüft, weil die Isotopensignatur mit Geologie und Klima der Anbauregion zusammenhängt. Fünf bis zehn Proben im Jahr sind wirksamer als jeder Marker.',
      '',
      'Zweitens die Token-Ownership. Kein Kaffeekäufer möchte Eigentümer eines Tokens werden, und es wirft wertpapier- und geldwäscherechtliche Fragen auf, die man ohne Not nicht aufwirft. Die Massenbilanz-Logik dahinter behalten wir vollständig — sie braucht nur keine Chain. Drittens Workflow-Engine und Single-Sign-on: bei unter hundert internen Nutzenden reiner Betriebsaufwand.',
      '',
      'Unten die Ersparnis: grob hundertfünfundsechzigtausend bis vierhundertneunzigtausend Euro einmalig. Und wir nennen den Preis dafür in einem Satz: Wir können einem Dritten die Zeitgleichheit unserer Belege nicht ohne unser Zutun beweisen. Danach fragt heute niemand — und ändert sich das, ist es nachrüstbar.',
    ].join('\n'),
  },
  {
    layout: 'bullets',
    kicker: 'Massenbilanz',
    title: 'Die Gleichung — und warum der Verlust eine Restgröße ist',
    speaker: 4,
    bullets: [
      ['Rösten ist eins zu eins, mit 15 bis 20 Prozent Verlust',
        'Der Verlust ist keine Konstante, sondern eine Funktion von Röstgrad, Ausgangsfeuchte und Chargengröße. Ein einziger unternehmensweiter Verlustfaktor ist fachlich falsch.'],
      ['Blenden ist n zu 1, mit 0,2 bis 1 Prozent Verlust',
        'Handling und Restmengen im Mischer. Die Rezepturtabelle führt je Blendcharge eine Zeile pro Bestandteil mit Ist-Masse und Ist-Anteil.'],
      ['Mahlen und Abpacken',
        'Mahlen 0,1 bis 0,5 Prozent. Kritisch ist die Mühlenspülung beim Sortenwechsel — sie wird als Ausschuss mit Grund-Code gebucht, nicht der neuen Charge zugeschlagen.'],
      ['Inputs werden gesperrt, nicht gelöscht',
        'Das übernehmen wir aus dem Referenzfall: verbrauchte Inputs erhalten den Status „locked" mit Grund-Code. Der Bestand bleibt rekonstruierbar.'],
    ],
    aside: {
      label: 'Erzwungene Bedingung',
      text: 'Σ Input\n=\nΣ Output\n+ Verlust\n+ Ausschuss\n+ Muster\n+ ε\n\n|ε| ≤ 0,5 %',
      size: 17,
    },
    takeaway: 'Ein- und Auswaage werden gewogen. Der Verlust ist die Restgröße — nicht der Eingabewert. Das dreht den Manipulationsvektor um.',
    source: 'Verlustbereiche [recherchiert bzw. geschätzt, je Prozess unterschiedlich]',
    notes: [
      'Zur zweiten Hälfte meines Blocks: der Massenbilanz.',
      '',
      'Die Gleichung rechts ist die aus dem Referenzfall, angepasst an Kaffee. Was hineingeht, muss dem entsprechen, was herauskommt, plus Prozessverlust, Ausschuss, entnommene Muster und eine Messtoleranz. Die Toleranz ist ausdrücklich begrenzt — wir schlagen ein halbes Prozent vor. Wird sie überschritten, gibt es einen Alarm, keine automatische Verbuchung.',
      '',
      'Und der wichtigste Satz steht unten: Ein- und Auswaage werden gewogen, der Verlust ist die Restgröße. Nicht umgekehrt. Warum das entscheidend ist, zeigt die nächste Folie.',
    ].join('\n'),
  },
  {
    layout: 'cards',
    kicker: 'Der Manipulationsvektor',
    title: 'Wie der Verlustfaktor belegt wird statt behauptet',
    speaker: 4,
    cols: 3,
    cards: [
      { badge: '1', title: 'Nie deklariert, immer gemessen', tone: 'good', text: 'Ein- und Auswaage kommen aus der angebundenen Waage. Ein manuell eingetragener Verlustfaktor ist im System schlicht nicht vorgesehen.' },
      { badge: '2', title: 'Korridor je Röstprofil', text: 'Aus historischen Chargen wird ein Erwartungsbereich kalibriert — Median plus robuste Streuung. Ein Profil gilt erst nach etwa zwanzig Chargen als kalibriert.' },
      { badge: '3', title: 'Ausreißer sind begründungspflichtig', text: 'Außerhalb des Korridors wird die Charge nicht blockiert, aber sie verlangt einen Grund-Code plus Freitext. Nicht begründete Ausreißer erscheinen im Monatsbericht.' },
      { badge: '4', title: 'Trend statt Einzelfall', text: 'Ein einzelner hoher Verlust ist Rauschen. Ein Trend ist das Signal. Kontrollkarte je Profil und je Schicht.' },
      { badge: '5', title: 'Der unabhängige Anker', tone: 'good', text: 'Grünkaffee-Einkauf minus Bestandsveränderung muss den Summen aller Einwaagen entsprechen. Diese Prüfung nutzt Belege außerhalb der Produktion: Rechnungen, Zollanmeldungen, Inventur.' },
      { badge: '!', title: 'Was übrig bleibt', tone: 'bad', text: 'Der Angriff ist reduziert auf: die Waage manipulieren UND die Einkaufsbuchhaltung fälschen. Dann ist es Urkundenfälschung, kein Datenqualitätsproblem.' },
    ],
    takeaway: 'Kein technisches System beseitigt das Risiko — auch der Referenzfall nicht, denn auch dort geht die Waagenmessung ungeprüft ins System. Unveränderlichkeit ist nicht Richtigkeit.',
    notes: [
      'Fünf Ebenen, gestaffelt, plus eine ehrliche Restlücke.',
      '',
      'Ebene eins: Der Verlust wird nie deklariert. Ein- und Auswaage kommen aus der angebundenen Waage, ein Eingabefeld für den Verlustfaktor existiert im System nicht. Das klingt banal, ist aber die wirksamste Einzelmaßnahme.',
      '',
      'Ebene zwei: ein Erwartungskorridor je Röstprofil, kalibriert aus historischen Chargen. Ein Profil gilt erst nach etwa zwanzig Chargen als kalibriert. Ebene drei: Ausreißer werden nicht blockiert, sondern sind begründungspflichtig — wer Chargen blockiert, erzeugt Umgehung; wer Begründungen verlangt, erzeugt eine Spur. Ebene vier: Wir schauen auf Trends, nicht auf Einzelfälle.',
      '',
      'Ebene fünf ist die stärkste und bemerkenswert unspektakulär: der Abgleich gegen Belege außerhalb der Produktion. Der Grünkaffee-Einkauf laut Rechnungen und Zollanmeldungen, minus Bestandsveränderung, muss der Summe aller Einwaagen entsprechen. Wer den Verlustfaktor manipulieren will, müsste zusätzlich die Einkaufsbuchhaltung fälschen.',
      '',
      'Damit zur letzten, rot markierten Karte. Diese fünf Ebenen reduzieren den Angriff auf: die Waage manipulieren und die Buchhaltung fälschen. Sie beseitigen ihn nicht. Kein technisches System kann das — auch das des Referenzfalls nicht, denn auch dort geht die Waagenmessung ungeprüft ins System. Wer etwas anderes behauptet, verwechselt Unveränderlichkeit mit Richtigkeit.',
    ].join('\n'),
  },
  {
    layout: 'flow',
    kicker: 'Blends',
    title: 'Vier Herkünfte, eine Tüte — ohne dabei zu täuschen',
    speaker: 4,
    steps: [
      { title: 'n Röstchargen', text: 'Jede mit eigener Herkunft und gewogener Ist-Masse' },
      { title: 'Rezepturtabelle', text: 'Je Bestandteil: Ist-Masse, Ist-Anteil, Soll-Anteil mit Toleranzband', emph: true },
      { title: 'Prüfung', text: 'Σ Input = Σ Output + Verlust + Toleranz — sonst Buchung blockiert' },
      { title: 'Produktpass', text: 'Anzeige speist sich aus dem Ist-Anteil dieser Charge, nie aus der Rezeptur', emph: true },
    ],
    breaks: {
      label: 'Vier Regeln gegen irreführende Herkunftsangaben',
      items: [
        '1 · Alle Bestandteile nennen, absteigend nach Anteil',
        '2 · Ist-Werte der Charge zeigen; Anteilsbänder nur, wenn Ist-Werte fehlen — und dann gekennzeichnet',
        '3 · Bestandteile unter 5 % nennen, nicht wegrunden',
        '4 · Keine Bauerngeschichte zu einem Blend, wenn der Bauer 12 % beiträgt',
      ],
    },
    takeaway: 'Weil sich die Zusammensetzung von Charge zu Charge ändert, ist die Losnummer im QR-Code zwingend — nicht optional.',
    notes: [
      'Letzte Folie meines Blocks: die Blends, also der Fall, den es bei Kakao so nicht gibt.',
      '',
      'Der wichtige Punkt ist der vierte Kasten: Die Anzeige im Produktpass speist sich aus dem Ist-Anteil dieser konkreten Charge, niemals aus der Rezeptur. Warum das nötig ist: Anteile werden chargenweise nachjustiert, je nach Ernte, Verfügbarkeit und Verkostung. Die Charge weiß, was in ihr ist — die Rezeptur weiß nur, was geplant war.',
      '',
      'Unten stehen vier Regeln gegen Irreführung. Alle Bestandteile nennen, absteigend nach Anteil. Ist-Werte zeigen; ein Anteilsband ist nur zulässig, wenn die Ist-Werte technisch nicht vorliegen, und muss dann gekennzeichnet sein. Bestandteile unter fünf Prozent werden genannt, nicht weggerundet.',
      '',
      'Daraus folgt die technische Konsequenz unten: Weil sich die Zusammensetzung von Charge zu Charge ändert, muss die Losnummer im QR-Code stehen. Sie ist zwingend, nicht optional. Damit übergebe ich an den letzten Block.',
    ].join('\n'),
  },
];

module.exports = { BLOCK_C, BLOCK_D };
