/** Inhalt Teil 4 — Block E: CO₂, Umsetzung, Risiken (Sprecher:in 5) und Backup-Folien. */

const BLOCK_E = [
  {
    layout: 'divider',
    num: 'E',
    title: 'CO₂, Umsetzung und Risiken',
    subtitle: 'Bilanzierung ohne Scheingenauigkeit, ein falsifizierbarer Pilot\nund unsere Empfehlung',
    speaker: 5,
    minutes: 10,
    notes: [
      'Danke. Ich schließe den Vortrag ab. Zuerst die CO₂-Bilanzierung — dort geht es weniger um Rechenverfahren als um die Frage, wie man mit Unsicherheit ehrlich umgeht.',
      'Dann der Zuschnitt eines Piloten, unsere Roadmap, die Kosten, die Risiken und zum Schluss unsere Empfehlung.',
    ].join(' '),
  },
  {
    layout: 'stats',
    kicker: 'CO₂ — die Größenordnungen zuerst',
    title: 'Wo die Emissionen wirklich liegen',
    speaker: 5,
    stats: [
      { value: '3,5–15,3', label: 'kg CO₂e je kg Grünkaffee', sub: 'Spannweite nach World Coffee Research für Anbau, Aufbereitung und Transport', size: 30 },
      { value: '> 84 %', label: 'Anteil des Anbaus', sub: 'am Cradle-to-Gate-Fußabdruck von gemahlenem Kaffee, laut LCA-Synthese', size: 36 },
      { value: '0,45–0,59', label: 'kg CO₂e je kg Röstkaffee', sub: 'Der gesamte Röstprozess. Rund 79 % davon entfallen auf den Brennstoff', size: 30 },
    ],
    note: 'Lesen Sie diese drei Zahlen zusammen: Die Spannweite des Grünkaffeewerts — Faktor 4,4 zwischen 3,5 und 15,3 — ist größer als unser gesamter Scope 1 und 2 zusammengenommen. Präzision bei uns im Haus verändert das Gesamtergebnis kaum; die Wahl des Emissionsfaktors für den Anbau verändert es massiv.',
    source: 'World Coffee Research · LCA-Synthese ScienceDirect · Röstprozess-LCA [recherchiert]',
    notes: [
      'Ein Kilogramm Grünkaffee verursacht je nach Quelle zwischen dreieinhalb und gut fünfzehn Kilogramm CO₂-Äquivalent. Über vierundachtzig Prozent davon entfallen auf den Anbau — nicht auf Transport, nicht auf Röstung. Unser eigener Röstprozess liegt bei knapp einem halben Kilogramm je Kilogramm Röstkaffee, wovon rund vier Fünftel auf den Brennstoff entfallen.',
      '',
      'Das heißt: Wenn wir unseren Gasverbrauch auf drei Nachkommastellen genau messen, verändert das das Gesamtergebnis praktisch nicht. Wählen wir dagegen einen anderen Emissionsfaktor für den Anbau, verändert sich das Ergebnis um mehrere hundert Prozent. Bei einer Rösterei liegen im Übrigen rund sechsundneunzig Prozent der Gesamtemissionen in Scope 3. Das ist der Rahmen, in dem wir uns bewegen.',
    ].join('\n'),
  },
  {
    layout: 'compare',
    kicker: 'Was messbar ist',
    title: 'Primärdaten dort, wo sie tatsächlich verfügbar sind',
    speaker: 5,
    columns: [
      {
        head: 'Scope 1 und 2 — messbar', sub: 'unsere eigene Rösterei',
        highlight: true,
        rows: [
          'Rösterbrenner: Impulsgaszähler, idealerweise je Maschine — Zählerstand bei Chargenstart und -ende',
          'Nachverbrenner: läuft auch zwischen Chargen. Leerlauf wird über die Tagesproduktion umgelegt',
          'Strom: Unterzähler je Maschine, sonst Allokation über Betriebsstunden',
          'Zwei Werte parallel führen: marktbasiert und standortbasiert',
          '= Chargengenau — aber nur mit nachgerüsteten Zählern',
        ],
      },
      {
        head: 'Scope 3 — überwiegend geschätzt', sub: 'der Löwenanteil',
        rows: [
          'Anbau und Aufbereitung: Emissionsfaktor je Land, Anbausystem und Aufbereitung, mit Unsicherheitsband',
          'Seetransport: Primärdaten liegen vor — Container, Route, Gewicht aus unseren eigenen Frachtpapieren. Also rechnen, nicht schätzen',
          'Verpackung: Herstellerangaben anfordern — hier ist Verbesserung realistisch',
          'Nutzungsphase beim Kunden: erheblich, und vollständig außerhalb unserer Kontrolle',
          '= Konsistenz ist wichtiger als Genauigkeit',
        ],
      },
    ],
    takeaway: 'Faktorquelle und -version werden je Berechnung mitgespeichert. Ein jährlich gewechselter Faktor macht jede Aussage über Fortschritt unmöglich.',
    source: 'Methodik nach GHG Protocol · Instrumentierungsaufwand [geschätzt]',
    notes: [
      'Der Rösterbrenner ist der saubere Fall: ein Impulsgaszähler je Maschine, und wir lesen den Zählerstand bei Chargenstart und -ende ab. Das ist echte, chargengenaue Messung.',
      '',
      'Beim Nachverbrenner wird es unsauber, und wir sagen das offen. Er läuft auch zwischen den Chargen, zum Warmhalten. Diesen Leerlauf legen wir über die Tagesproduktion um — das ist eine Allokation, keine Messung, und wir weisen sie getrennt aus. Wer beides zu einer Zahl addiert und gemessen nennt, macht denselben Fehler wie bei Scope 3.',
      '',
      'Rechts Scope 3. Hier ist eine Differenzierung wichtig, die oft unterbleibt. Beim Anbau kommen wir um Sekundärfaktoren nicht herum — eine echte Feld-Ökobilanz je Kooperative kostet fünfstellig. Aber der Seetransport ist anders: Container, Route und Gewicht stehen in unseren eigenen Frachtpapieren. Diese Primärdaten sind praktisch umsonst zu haben, die soll man rechnen, nicht schätzen.',
    ].join('\n'),
  },
  {
    layout: 'cards',
    kicker: 'Gegen Scheingenauigkeit',
    title: 'Fünf Regeln, die im System stehen — nicht im Redaktionsleitfaden',
    speaker: 5,
    cols: 3,
    cards: [
      { badge: '1', title: 'Keine Nachkommastelle ohne Deckung', text: 'Bei einer Spanne von 3,5 bis 15,3 kg ist die Ausgabe „7,43 kg CO₂e pro kg" unseriös. Ausgabe als Bereich oder gerundet mit Bandbreitenangabe.' },
      { badge: '2', title: 'Primär und sekundär getrennt ausweisen', tone: 'good', text: 'Jede CO₂-Position trägt eine Stufe: gemessen, gerechnet oder geschätzt. Das ist das direkte Gegenstück zum Evidence Grading.' },
      { badge: '3', title: 'Allokationen kennzeichnen', text: 'Der umgelegte Nachverbrenner-Leerlauf ist keine Messung — und darf im Ergebnis nicht so aussehen.' },
      { badge: '4', title: 'Keine Kompensation in derselben Zahl', tone: 'bad', text: 'Zertifikate werden getrennt ausgewiesen, nie vom Fußabdruck abgezogen. Das Wort „klimaneutral" erscheint im Produktpass nicht.' },
      { badge: '5', title: 'Nutzungsphase nennen oder weglassen', text: 'Nie stillschweigend ausklammern, wenn die Zahl als „Fußabdruck einer Tasse" kommuniziert wird. Die Zubereitung beim Kunden ist erheblich.' },
      { badge: '→', title: 'Was daraus im Produktpass steht', text: '„ca. 6–13 kg CO₂e je kg Röstkaffee. Davon in unserer Rösterei gemessen: 0,52 kg. Der Rest beruht auf Durchschnittswerten der Fachliteratur, nicht auf Messungen bei unseren Erzeugern."' },
    ],
    takeaway: 'Weniger verkaufsstark als „2,1 kg — klimaneutral", und um Größenordnungen ehrlicher. Es ist außerdem das Einzige, was einer Prüfung auf irreführende Umweltaussagen standhält.',
    source: 'Anforderung an substantiierte Umweltaussagen u. a. aus RL (EU) 2024/825 und UWG [angenommen]',
    notes: [
      'Diese fünf Regeln sind als Systemverhalten gedacht, nicht als Redaktionsrichtlinie. Der Unterschied ist wichtig: Eine Richtlinie wird unter Zeitdruck gebrochen, eine Systemregel nicht.',
      '',
      'Regel eins: keine Nachkommastelle, welche die Unsicherheit nicht trägt. Bei einer Spanne von dreieinhalb bis fünfzehn Kilogramm ist die Angabe sieben Komma vier drei schlicht unseriös. Regel zwei ist das Gegenstück zum Evidence Grading: Jede Position trägt eine Stufe — gemessen, gerechnet oder geschätzt.',
      '',
      'Das ist weniger verkaufsstark als zwei Komma eins Kilogramm, klimaneutral. Es ist um Größenordnungen ehrlicher und das Einzige, was einer Prüfung auf irreführende Umweltaussagen standhält.',
    ].join('\n'),
  },
  {
    layout: 'cards',
    kicker: 'Der Pilot',
    title: 'Vier Hypothesen, die der Pilot widerlegen kann',
    speaker: 5,
    cols: 2,
    cards: [
      { badge: 'H1', title: 'Datenkette', text: 'Für mindestens 95 % der Masse einer Röstcharge ist die Kette bis zur Parzelle rekonstruierbar.\n\nErwartung: teilweise widerlegt — bis zur Kooperative ja, bis zur Parzelle nicht.' },
      { badge: 'H2', title: 'Betriebliche Tragfähigkeit', tone: 'bad', text: 'Erfassung höchstens zwei Minuten je Charge, Quote nach acht Wochen ohne Nachfassen bei 95 %.\n\nScheitert am häufigsten, wird am seltensten gemessen.' },
      { badge: 'H3', title: 'Beschaffbarkeit', text: 'Die Kooperative liefert Parzellendaten in geforderter Qualität ohne Zusatzvergütung über den bestehenden Preis hinaus.\n\nWird sie widerlegt, bestimmt das direkt die Skalierungskosten.' },
      { badge: 'H4', title: 'Zahlungsbereitschaft', tone: 'good', text: 'Mindestens ein Handelskunde ist bereit, für chargengenaue Herkunfts- und CO₂-Daten einen benannten Aufpreis oder eine Vertragsbindung zu geben.\n\nWird H4 widerlegt, entfällt die Geschäftsgrundlage für die Verankerung vollständig.' },
    ],
    takeaway: 'Ein Pilot, der nichts widerlegen kann, ist eine Demo. Zuschnitt: eine Herkunft, eine Single-Origin-SKU, ein Röstprofil, ein Röster — bewusst ohne Blend.',
    notes: [
      'Zum Piloten. Hier ist uns eine Formulierung aus der Wissenschaftstheorie wichtig: Ein Pilot, der nichts widerlegen kann, ist keine Untersuchung, sondern eine Demonstration. Wir haben deshalb vier Hypothesen so formuliert, dass sie scheitern können.',
      '',
      'Hypothese zwei ist rot markiert, weil sie am ehesten scheitert und am seltensten gemessen wird: Kostet die Erfassung höchstens zwei Minuten je Charge, und liegt die Quote nach acht Wochen ohne Nachfassen noch bei fünfundneunzig Prozent? Wichtig ist das ohne Nachfassen — sonst misst man die Erinnerung und nicht das System.',
      '',
      'Hypothese drei betrifft die Beschaffbarkeit der Herkunftsdaten und bestimmt direkt die Skalierungskosten. Und Hypothese vier ist die kommerzielle: Ist ein Handelskunde bereit, dafür zu zahlen? Wird sie widerlegt, entfällt die Geschäftsgrundlage für die Verankerung vollständig. Die konkrete Frage lautet deshalb nicht finden Sie das interessant, sondern würden Sie es vertraglich verlangen und dafür zahlen.',
    ].join('\n'),
  },
  {
    layout: 'timeline',
    kicker: 'Roadmap',
    title: 'Drei Phasen — streng getrennt',
    speaker: 5,
    phases: [
      { num: '0', title: 'Compliance', when: 'jetzt bis 30.12.2026', text: 'EUDR-Fähigkeit: Rollenklärung, Geodaten, Risikoprüfung, Sorgfaltserklärungen, Referenznummern-Register.\n\nPflicht. Muss auch dann stehen, wenn alles andere gestrichen wird. Zugekaufte Software, kein Eigenbau, kein Ledger.', emph: true },
      { num: '1', title: 'Datenqualität', when: '2027', text: 'Chargenmodell nach EPCIS, Evidence Grading, CO₂ Scope 1 und 2 je Röstcharge, freiwilliger Produktpass für eine Pilot-SKU.\n\nFreiwilliger Mehrwert. Zahlt auf Einkauf, Qualität, Rückruffähigkeit und Vertrieb ein.' },
      { num: '2', title: 'Verankerung', when: 'frühestens 2028', text: 'Kryptografische Nachweisbarkeit der Zeitgleichheit.\n\nStartet NUR bei einem von vier Auslösekriterien — sonst gar nicht. Auch nicht „für später schon mal".' },
    ],
    takeaway: 'Kritischer Pfad in Phase 0 ist die Geodatenbeschaffung, nicht die Software. Frühwarnung: Sind bis KW 43 nicht 80 % der Direct-Trade-Menge unterlegt, müssen Herkünfte auf Importeursbezug umgestellt werden.',
    notes: [
      'Unsere Roadmap hat drei Phasen, und die Trennung ist uns wichtiger als die Inhalte.',
      '',
      'Phase 0 ist Pflicht und läuft bis zum 30. Dezember 2026: Rollenklärung, Geodaten, Risikoprüfung, Sorgfaltserklärungen, Referenznummern-Register. Zugekaufte Software, kein Eigenbau, kein Ledger. Diese Phase muss auch dann stehen, wenn alles andere gestrichen wird — sie ist der Preis der Marktzugehörigkeit.',
      '',
      'Phase 2 startet frühestens 2028 und nur bei einem von vier Auslösekriterien: Ein benannter Kunde verlangt sie vertraglich; eine Regulierungsänderung verlangt mehr als einen qualifizierten Zeitstempel; zwei externe Parteien sollen in denselben Bestand schreiben und misstrauen einander; oder ein Schadensfall hat gezeigt, dass unsere Dokumentation extern nicht akzeptiert wurde. Fehlen alle vier, wird Phase 2 nicht gestartet — auch nicht für später schon mal. Genau so entstehen Systeme, die niemand braucht.',
      '',
      'Die wichtigste Warnung steht unten: Der kritische Pfad in Phase 0 ist die Geodatenbeschaffung, nicht die Software. Wir schlagen eine Frühwarnschwelle vor: Sind bis Kalenderwoche 43 nicht achtzig Prozent der Direct-Trade-Menge unterlegt, muss über die Umstellung betroffener Herkünfte auf Importeursbezug entschieden werden. Das kostet Marge, erhält aber die Verkaufsfähigkeit — und die Entscheidung im Voraus zu treffen ist erheblich billiger, als sie im Dezember treffen zu müssen.',
    ].join('\n'),
  },
  {
    layout: 'stats',
    kicker: 'Kosten',
    title: 'Drei Jahre, Bandbreiten statt Punktwerten',
    speaker: 5,
    stats: [
      { value: '151–475 T€', label: 'Nur Phase 0', sub: 'Die Minimalvariante. Reine Pflichterfüllung, kein Produktpass, kein Ledger', size: 26 },
      { value: '312–878 T€', label: 'Phase 0 + 1, Option B', sub: 'Unsere Empfehlung. Compliance plus Datenqualität, Verankerung vorbereitet', size: 26 },
      { value: '526–1.615 T€', label: 'Phase 0 + 1 + 2, Option C', sub: 'Der Referenzfall-Klon mit Plattform, Ledger, Token und Markern', size: 24 },
    ],
    note: 'Die Spannen sind breit, weil ein einziger Posten sie dominiert: die Geodatenbeschaffung upstream — zwischen 5.000 € und 60.000 € je nachdem, ob die Kooperativen bereits kartiert sind. Nicht die Software ist das Teure. Die Daten sind das Teure, und die liegen in Äthiopien, Kolumbien und Honduras.',
    takeaway: 'Vor Freigabe von Phase 1 sollte die Bestandsaufnahme der Geodaten abgeschlossen sein — sie halbiert die Unsicherheit der größten Position.',
    source: 'Alle Werte [geschätzt], Bandbreiten über drei Jahre inkl. laufendem Betrieb',
    notes: [
      'Jetzt zur Breite der Spannen, die man uns zu Recht vorhalten kann. Sie kommt fast vollständig von einem einzigen Posten: der Geodatenbeschaffung. Die kann null Euro kosten, wenn die Kooperative über Fairtrace bereits kartiert ist — oder drei- bis achttausend Euro je Kooperative, wenn wir einen Kartierungsdienstleister beauftragen müssen. Über acht bis fünfzehn Herkünfte summiert sich das auf fünftausend bis sechzigtausend Euro.',
      '',
      'Der Merksatz zu dieser Folie: Nicht die Software ist das Teure. Die Daten sind das Teure, und die liegen in Äthiopien, Kolumbien und Honduras.',
    ].join('\n'),
  },
  {
    layout: 'compare',
    kicker: 'Risiken',
    title: 'Adressiert das Design das Risiko — oder verlagert es nur?',
    speaker: 5,
    columns: [
      {
        head: 'Nur verlagert', sub: 'ehrlich benannt',
        rows: [
          'Garbage in: Eine plausible falsche Koordinate erkennt kein System. Im verankerten Zustand wird der Fehler zusätzlich unveränderlich — das verschlechtert die Lage',
          'Kollusion: Stimmen Kooperative und Exporteur sich ab, ist das aus den Daten nicht erkennbar. Wirksam sind nur Isotopenanalyse und Vor-Ort-Audit',
          'Adoptionsverweigerung upstream: kein technisches Problem, sondern ein Beschaffungs- und Beziehungsthema',
          '= Ein Ledger sichert die Integrität der Aufzeichnung, nicht die der Aussage',
        ],
      },
      {
        head: 'Wirklich adressiert', sub: 'mit benannter Restlücke',
        highlight: true,
        rows: [
          'Verlustfaktor-Manipulation: fünf Ebenen, die stärkste nutzt Belege außerhalb der Produktion',
          'Anbieter-Lock-in: EPCIS als Standardformat, eigene Datenkopie, austauschbare Verankerungssenke',
          'Regulatorische Änderung: Regelinterpretation wird gekauft, nicht gebaut; das Datenmodell ist fachlich geschnitten',
          '= Restrisiken bleiben, sie sind aber benannt und begrenzt',
        ],
      },
    ],
    takeaway: 'Drei Risiken können das Projekt beenden, und keines davon ist technisch: Upstream liefert nicht · die Röstmannschaft erfasst nicht · niemand fragt nach dem Ergebnis.',
    notes: [
      'Bei den Risiken haben wir uns eine Bewertungsfrage auferlegt, die in Risikotabellen selten gestellt wird: Adressiert das Design das Risiko wirklich, oder verlagert es das Problem nur? Bei drei von sechs Risiken lautet die ehrliche Antwort: verlagert.',
      '',
      'Erstens Garbage in. Unser System fängt grobe Fehler über Plausibilitätsprüfungen ab — Polygonüberlappung, Ertrag je Hektar, Höhenlage. Eine plausible falsche Koordinate erkennt es nicht. Und jetzt der Punkt, der gegen eine frühe Verankerung spricht: In einem verankerten System wird ein solcher Fehler zusätzlich unveränderlich. Die Blockchain verschlechtert hier die Lage. Deshalb unsere Regel: verankern erst, wenn die Erfassungsqualität stabil ist — niemals am Anfang.',
      '',
      'Zweitens Kollusion. Wenn Kooperative und Exporteur sich absprechen, ist das aus den Daten nicht erkennbar. Wirksam sind nur unabhängige physische Messung und Vor-Ort-Audits. Wer Blockchain gegen Kollusion anführt, hat das Problem nicht verstanden: Ein Ledger sichert die Integrität der Aufzeichnung, nicht die der Aussage. Drittens Adoptionsverweigerung upstream — kein technisches Problem, sondern ein Beschaffungsthema.',
      '',
      'Und unten die Zusammenfassung, die wir für den ehrlichsten Satz unseres Projekts halten: Drei Risiken können dieses Projekt beenden, und keines davon ist technisch. Upstream liefert nicht. Die Röstmannschaft erfasst nicht. Und niemand fragt nach dem Ergebnis. Jede Projektsteuerung sollte diese drei zuerst messen.',
    ].join('\n'),
  },
  {
    layout: 'statement',
    kicker: 'Fazit',
    statement: 'Wer sauberes Lieferanten-\nmanagement, verlässliche Parzellen-\ndaten und ein durchgängiges\nChargenmodell hat, hat 90 % des\nNutzens — ohne einen einzigen Hash.',
    size: 27,
    points: [
      'Phase 0 ist Pflicht und terminkritisch: 30.12.2026, und der Engpass liegt upstream, nicht in der IT',
      'Der digitale Produktpass ist für Kaffee freiwillig — wer ihn als Pflicht verkauft, irrt oder verkauft',
      'Die Verankerung ist das letzte Prozent. Sie ist erst sinnvoll, wenn jemand dafür zahlt',
      'Unsere Empfehlung: Option B — Compliance kaufen, Datenschicht schlank selbst bauen, Verankerung vorbereiten statt aktivieren',
    ],
    notes: [
      'Wenn dieses Unternehmen am Ende sauberes Lieferantenmanagement hat, verlässliche Parzellendaten, ein durchgängiges Chargenmodell und eine testierte Auswertung — dann hat es neunzig Prozent des Nutzens. Völlig unabhängig davon, ob je ein Hash auf einem Ledger landet.',
      '',
      'Vier Punkte zum Mitnehmen. Erstens: Phase 0 ist Pflicht und terminkritisch. Der 30. Dezember 2026 steht, und der Engpass liegt upstream bei den Kooperativen, nicht in der IT-Abteilung. Wer jetzt Architekturdiskussionen führt statt Lieferantendaten zu beschaffen, verfehlt die Frist mit einer schönen Präsentation.',
      '',
      'Zweitens: Der digitale Produktpass ist für Kaffee freiwillig. Das war unser überraschendster Befund, und er ist am Verordnungstext nachprüfbar.',
      '',
      'Drittens: Die Verankerung ist das letzte Prozent und erst sinnvoll, wenn jemand dafür zahlt. Wir haben sie deshalb nicht gestrichen, sondern vorbereitet — der Wechsel bleibt eine Konfigurationsänderung.',
      '',
      'Viertens unsere Empfehlung: Option B. Compliance kaufen, weil sich dort die Regeln schneller ändern, als man nachpflegen kann. Die Datenschicht schlank selbst bauen, weil sie der differenzierende Teil ist. Und die Verankerung vorbereiten statt aktivieren.',
      '',
      'Wenn wir eine einzige Sache aus diesem Projekt mitnehmen, dann diese: Die interessanteste Leistung in einem solchen Vorhaben ist nicht, was man baut. Es ist, was man mit Begründung weglässt.',
      '',
      'Vielen Dank für Ihre Aufmerksamkeit. Wir freuen uns auf Ihre Fragen — für Details haben wir Backup-Folien vorbereitet.',
    ].join('\n'),
  },
];

const BACKUP = [
  {
    layout: 'divider',
    num: 'B',
    title: 'Backup',
    subtitle: 'Detailfolien für Ihre Rückfragen',
    speaker: '1–5',
    minutes: 0,
    notes: 'Ab hier folgen Backup-Folien. Wir zeigen sie nur, wenn eine Frage darauf zielt: die EUDR-Pflichtangaben, die Kostentabelle, die Sonderfälle der Massenbilanz, die Emissionsfaktoren, die Regeln des Evidence Gradings, die offenen Fragen und das Quellenverzeichnis.',
  },
  {
    layout: 'table',
    kicker: 'Backup 1',
    title: 'EUDR — Pflichtangaben je Direct-Trade-Lot',
    head: ['Angabe', 'Inhalt', 'Quelle im Feld'],
    colW: [3.0, 5.6, 3.33],
    rows: [
      ['Geolokation', 'Polygon ab 4 ha, sonst Punktkoordinate; muss Satellitenprüfung standhalten', 'Kooperative, Exporteur, Fairtrace'],
      ['Erntezeitraum', 'Je Parzelle, nicht je Lot', 'Kooperative'],
      ['Legalität', 'Landnutzung, Arbeitsrecht, Steuern, Handelsrecht — nach Recht des Erzeugerlandes', 'Exporteur, Behördendokumente'],
      ['Entwaldungsfreiheit', 'Kein Waldverlust nach dem 31.12.2020 auf der Fläche', 'Abgleich Polygon gegen Waldverlustdaten'],
      ['Risikobewertung', 'Dokumentiert; bei nicht vernachlässigbarem Risiko zuerst Minderung', 'Eigene Analyse bzw. Compliance-Software'],
      ['Sorgfaltserklärung', 'Einreichung in TRACES vor dem Inverkehrbringen', 'Eigene Abgabe'],
      ['Referenznummer', 'Sichern und an eigene Abnehmer weitergeben', 'Aus TRACES'],
    ],
    source: 'VO (EU) 2023/1115 i. d. F. VO (EU) 2025/2650 [recherchiert]',
    notes: 'Backup zu den EUDR-Pflichtangaben. Die rechte Spalte ist die praktisch wichtigste: Sie zeigt, dass wir fast nichts davon selbst erheben — wir sammeln es ein. Genau deshalb liegt der Engpass upstream.',
  },
  {
    layout: 'table',
    kicker: 'Backup 2',
    title: 'Kosten im Detail — Bandbreiten und Treiber',
    head: ['Position', 'Einmalig', 'Laufend p. a.'],
    colW: [5.6, 3.2, 3.13],
    rows: [
      ['Phase 0 — Rechtsberatung Rollen und Gutachten', '8.000 – 20.000 €', '—'],
      ['Phase 0 — EUDR-Software, Einführung und Konfiguration', '10.000 – 35.000 €', '12.000 – 40.000 €'],
      ['Phase 0 — Geodatenbeschaffung (größte Unsicherheit)', '5.000 – 60.000 €', '5.000 – 25.000 €'],
      ['Phase 0 — Verträge, ERP-Anbindung, Schulung', '16.000 – 45.000 €', '20.000 – 40.000 €'],
      ['Phase 1 — Röstsoftware mit Chargenverwaltung', '10.000 – 25.000 €', 'in Lizenz enthalten'],
      ['Phase 1 — Event Store, Konnektoren, Evidence Grading', '40.000 – 90.000 €', '23.000 – 59.000 €'],
      ['Phase 1 — Produktpass, QR, B2B-Schnittstelle', '20.000 – 45.000 €', 'in Wartung enthalten'],
      ['Phase 1 — Zähler-Nachrüstung und CO₂-Methodik', '14.000 – 45.000 €', '5.000 – 15.000 €'],
      ['Phase 2 — Verankerung: Anbindung, Schlüssel, Rechtsprüfung', '16.000 – 52.000 €', '2.000 – 6.000 €'],
      ['Phase 2 — Ledger-Transaktionsgebühren', '—', '0 – 400 €'],
    ],
    source: 'Alle Werte [geschätzt] · Hedera-Gebühren [recherchiert]',
    notes: 'Die Kostentabelle im Detail. Beachten Sie die letzte Zeile: Die Ledger-Gebühren stehen bewusst mit drin, damit sichtbar wird, wie klein sie im Verhältnis zu allem anderen sind.',
  },
  {
    layout: 'table',
    kicker: 'Backup 3',
    title: 'Massenbilanz — Sonderfälle vollständig',
    head: ['Fall', 'Behandlung'],
    colW: [3.6, 8.33],
    rows: [
      ['Fehlröstung', 'Eigene Buchung mit Grund-Code, Masse bleibt in der Bilanz. Verkauf als B-Ware nur mit eigener Chargen-ID und ohne Herkunftsauslobung'],
      ['Musterröstung, Cupping', 'Grund-Code „sample". Wichtig: vom Verlustkorridor ausgeschlossen, sonst verzerren Kleinstmengen die Kalibrierung'],
      ['Retouren', 'Rückbuchung auf die ursprüngliche Chargen-ID, Status „returned". Kein Wiedereinlagern ohne Qualitätsfreigabe'],
      ['Restbestände im Silo', 'Herkunftsgebunden als Teilmenge geführt. Setzt FIFO-Disziplin voraus — ohne sie ist die Zuordnung Fiktion und muss so gekennzeichnet werden'],
      ['Verlesen und Sieben im Haus', 'Eigene 1:1-Transformation vor dem Rösten. Sonst erscheint der Verlesungsverlust fälschlich als Röstverlust'],
      ['Entkoffeinierung extern', 'Lohnverarbeitung mit Ein- und Ausgangsgewicht des Dienstleisters. Deutlich höherer, verfahrensabhängiger Verlust — eigener Korridor'],
      ['Mühlenspülung bei Sortenwechsel', 'Grund-Code „purge" als Ausschuss, nie der neuen Charge zugeschlagen'],
      ['Inventurdifferenz', 'Nie stillschweigend ausbuchen. Eigener Grund-Code, Betragsgrenze mit Freigabepflicht. Das ist das Schlupfloch, durch das in der Praxis am meisten verschwindet'],
    ],
    notes: 'Die Sonderfälle. Die letzte Zeile ist die wichtigste: Inventurdifferenzen sind in der Praxis das größte Schlupfloch, weil sie so harmlos aussehen.',
  },
  {
    layout: 'table',
    kicker: 'Backup 4',
    title: 'CO₂ — Referenzwerte und ihre Quellen',
    head: ['Position', 'Wert', 'Status'],
    colW: [5.0, 3.6, 3.33],
    rows: [
      ['Grünkaffee cradle-to-gate', '3,51 – 15,33 kg CO₂e/kg', 'recherchiert, World Coffee Research'],
      ['Alternativer Referenzwert', '~11 kg CO₂e/kg', 'recherchiert, ICO-Schätzung'],
      ['Anteil Anbau am Fußabdruck', '> 84 %', 'recherchiert, LCA-Synthese'],
      ['Röstprozess gesamt', '0,45 – 0,59 kg CO₂e/kg', 'recherchiert, Fallstudien'],
      ['Brennstoffanteil am Röstprozess', '~79 %', 'recherchiert, LPG-Fallstudie'],
      ['Scope-3-Anteil einer Rösterei', '~96 %', 'recherchiert, Fallstudie'],
      ['Unsere Angabe im Produktpass', 'ca. 6 – 13 kg CO₂e/kg', 'abgeleitet, als Bereich ausgewiesen'],
    ],
    source: 'World Coffee Research · ICO · ScienceDirect LCA-Synthese · Kaffeemacher-Bilanz [recherchiert]',
    notes: 'Die CO₂-Referenzwerte mit Quellenstatus. Die letzte Zeile zeigt, wie wir daraus unsere eigene Angabe ableiten — als Bereich, nicht als Punktwert.',
  },
  {
    layout: 'table',
    kicker: 'Backup 5',
    title: 'Evidence Grading — die vier Stufen',
    head: ['Stufe', 'Definition', 'Beispiel bei uns'],
    colW: [2.2, 6.2, 3.53],
    rows: [
      ['Verified', 'Zeitgleich erfasst, signiert von identifiziertem Erfasser oder Gerät, seither unverändert', 'Auswaage der Röstcharge; Gaszählerstand'],
      ['Declared', 'Von benannter Partei erklärt, aber nicht zeitgleich oder nicht selbst signiert', 'Parzellendaten, erfasst durch die Kooperative'],
      ['Imported', 'Aus Altsystem oder Datei übernommen, ohne Erfassungskontext', 'Historische ERP-Chargendaten; Excel des Exporteurs'],
      ['Estimated', 'Berechnet oder aus Sekundärquellen abgeleitet', 'CO₂-Anteil Anbau; umgelegter Nachverbrenner-Leerlauf'],
    ],
    source: 'Kommunikationsregel: keine Symbole für Declared, kein Trust Score, keine Gesamtnote',
    notes: 'Die vier Stufen im Überblick. Wichtig ist die Zeile unten: Für Declared verwenden wir keine Symbole und keine Farben, nur Text — sonst liest es sich wie eine Auszeichnung.',
  },
  {
    layout: 'table',
    kicker: 'Backup 6',
    title: 'Offene Fragen, die vor dem Bauen zu klären sind',
    head: ['Frage', 'Warum sie blockiert'],
    colW: [4.6, 7.33],
    rows: [
      ['Wer ist Zollanmelder je Bezugsquelle?', 'Entscheidet über Primärbetreiber oder nachgelagert — und damit über den halben Umsetzungsaufwand'],
      ['Löst Rösten ein erneutes Inverkehrbringen aus?', 'Bestimmt, ob für zugekaufte Ware nach der Röstung eine eigene Erklärung nötig ist'],
      ['Welche Herkünfte sind bereits kartiert?', 'Größte Kostenposition und kritischer Pfad zugleich'],
      ['Sichern Importeure die Referenznummern vertraglich zu?', 'Ohne Nummer darf die Ware nicht weitergegeben werden — Produktionsstillstand'],
      ['Sind wir bestätigt mittleres/großes Unternehmen?', 'Entscheidet zwischen 30.12.2026 und 30.06.2027. Eine Stunde Arbeit, sechs Monate Wirkung'],
      ['Segregation oder Silo-Vermischung im Lager?', 'Die folgenreichste Nicht-IT-Entscheidung: Sie bestimmt, ob die Chargenzuordnung real oder Fiktion ist'],
      ['Fragt ein B2B-Kunde nach mehr als der Referenznummer?', 'Entscheidet über die Existenzberechtigung von Phase 2'],
    ],
    notes: 'Die offenen Fragen. Die fünfte ist unser Lieblingshinweis an das Unternehmen: Die Größenklassenprüfung kostet eine Stunde und kann sechs Monate Frist schenken.',
  },
  {
    layout: 'table',
    kicker: 'Backup 7',
    title: 'Quellenverzeichnis (Auswahl)',
    head: ['Thema', 'Quelle'],
    colW: [3.8, 8.13],
    rows: [
      ['EUDR-Revision und Fristen', 'VO (EU) 2025/2650, EUR-Lex · Rat der EU, Pressemitteilung 18.12.2025'],
      ['EUDR-Grundverordnung', 'VO (EU) 2023/1115, EUR-Lex'],
      ['Vereinfachungspaket und Umsetzung', 'Europäische Kommission, 04.05.2026 und 13.07.2026'],
      ['ESPR und Lebensmittelausnahme', 'VO (EU) 2024/1781, Art. 1 Abs. 2, EUR-Lex · ESPR-Arbeitsplan 16.04.2025'],
      ['Verpackungsverordnung', 'VO (EU) 2025/40 · DIHK-Merkblatt PPWR'],
      ['Datenstandard', 'GS1 EPCIS 2.0 · GS1 Germany EUDR Implementation Guideline v1.11'],
      ['Geodaten und Polygonqualität', 'Koltiva · Fairtrade Fairtrace, Daily Coffee News 16.06.2026'],
      ['Ledger-Kosten', 'Hedera, Preisänderung ConsensusSubmitMessage, Januar 2026'],
      ['CO₂-Referenzwerte', 'World Coffee Research · ICO · ScienceDirect LCA-Synthese'],
      ['Referenzfall', 'Pressemitteilung Hashgraph Group / Merck / PwC Germany, 08.09.2026'],
    ],
    source: 'Vollständige Quellenangaben mit Links in den Planungsdokumenten unter plan/ · Rechercheschluss 09.09.2026',
    notes: 'Das Quellenverzeichnis in Auswahl. Die vollständigen Angaben mit Links stehen in unseren Planungsdokumenten im Repository. Unser Rechercheschluss war der 9. September 2026.',
  },
];

module.exports = { BLOCK_E, BACKUP };
